import { InsightsSection } from "@repo/api/src/types/insights";

export const TileKind = {
  Kpi: "kpi",
  CategoryBar: "category-bar",
  Donut: "donut",
  Heatmap: "heatmap",
  TimeSeries: "timeseries",
  TimeSeriesBar: "timeseries-bar",
  ReviewerTable: "reviewer-table",
} as const;
export type TileKind = (typeof TileKind)[keyof typeof TileKind];

export type TileGroupBy = {
  key: string;
  label: string;
};

export type TileDescriptor = {
  id: string;
  section: InsightsSection;
  title: string;
  kind: TileKind;
  dataKey: string;
  metricKey: string;
  metricLabel: string;
  unitLabel?: string;
  groupBy?: TileGroupBy;
  horizontal?: boolean;
  // Render each category's value directly on the bar (in addition to the hover
  // tooltip) so it's readable at a glance. Opt-in per tile; category-bar only.
  showValueLabels?: boolean;
  infoKey?: string;
  grid: { w: number; h: number };
};

const KPI_GRID = { w: 3, h: 2 } as const;
const CHART_GRID = { w: 6, h: 4 } as const;
const WIDE_GRID = { w: 12, h: 4 } as const;

function kpiTile(
  section: InsightsSection,
  key: string,
  title: string,
  metricLabel = title,
  unitLabel?: string
): TileDescriptor {
  return {
    id: `kpi:${key}`,
    section,
    title,
    kind: TileKind.Kpi,
    dataKey: key,
    metricKey: key,
    metricLabel,
    ...(unitLabel ? { unitLabel } : {}),
    grid: KPI_GRID,
  };
}

function chartTile(
  input: Omit<TileDescriptor, "grid"> & {
    wide?: boolean;
  }
): TileDescriptor {
  return {
    ...input,
    grid: input.wide ? WIDE_GRID : CHART_GRID,
  };
}

export const INSIGHTS_TILES: TileDescriptor[] = [
  // Delivery & efficiency.
  kpiTile(InsightsSection.Delivery, "merged", "Merged PRs", "Pull requests"),
  kpiTile(
    InsightsSection.Delivery,
    "ttm",
    "Median time to merge",
    "Time to merge"
  ),
  kpiTile(
    InsightsSection.Delivery,
    "kloc",
    "KLOC merged",
    "KLOC merged",
    "KLOC"
  ),
  kpiTile(InsightsSection.Delivery, "cost", "Cost"),
  kpiTile(InsightsSection.Delivery, "merge-rate", "Merge rate"),
  kpiTile(
    InsightsSection.Delivery,
    "pr-size",
    "Median PR size",
    "Median PR size",
    "lines"
  ),
  chartTile({
    id: "chart:klocTrend",
    section: InsightsSection.Delivery,
    title: "KLOC merged over time",
    kind: TileKind.TimeSeries,
    dataKey: "klocTrend",
    metricKey: "kloc",
    metricLabel: "KLOC merged",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:klocTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:klocTrend:bar",
    section: InsightsSection.Delivery,
    title: "KLOC merged by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "klocTrend",
    metricKey: "kloc",
    metricLabel: "KLOC merged",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:klocTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:klocTrend:heatmap",
    section: InsightsSection.Delivery,
    title: "KLOC merged heatmap",
    kind: TileKind.Heatmap,
    dataKey: "klocTrend",
    metricKey: "kloc",
    metricLabel: "KLOC merged",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:klocTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:prTrend",
    section: InsightsSection.Delivery,
    title: "PR throughput",
    kind: TileKind.TimeSeries,
    dataKey: "prTrend",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:prTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:prTrend:heatmap",
    section: InsightsSection.Delivery,
    title: "PR activity heatmap",
    kind: TileKind.Heatmap,
    dataKey: "prTrend",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:prTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:prTrend:bar",
    section: InsightsSection.Delivery,
    title: "PR throughput by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "prTrend",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:prTrend",
    wide: true,
  }),
  chartTile({
    id: "chart:prByRepo",
    section: InsightsSection.Delivery,
    title: "Merged PRs by repository",
    kind: TileKind.CategoryBar,
    dataKey: "prByRepo",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "repo", label: "Repository" },
    horizontal: true,
    infoKey: "chart:prByRepo",
  }),
  chartTile({
    id: "chart:prByRepo:donut",
    section: InsightsSection.Delivery,
    title: "PR share by repository",
    kind: TileKind.Donut,
    dataKey: "prByRepo",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "repo", label: "Repository" },
    infoKey: "chart:prByRepo",
  }),
  chartTile({
    id: "chart:prByState",
    section: InsightsSection.Delivery,
    title: "PR distribution",
    kind: TileKind.CategoryBar,
    dataKey: "prByState",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "state", label: "State" },
    infoKey: "chart:prByState",
  }),
  chartTile({
    id: "chart:prByState:donut",
    section: InsightsSection.Delivery,
    title: "PR distribution",
    kind: TileKind.Donut,
    dataKey: "prByState",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "state", label: "State" },
    infoKey: "chart:prByState",
  }),
  chartTile({
    id: "chart:checkStatus",
    section: InsightsSection.Delivery,
    title: "Check status",
    kind: TileKind.Donut,
    dataKey: "checkStatus",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "check-status", label: "Check status" },
    infoKey: "chart:checkStatus",
  }),
  chartTile({
    id: "chart:checkStatus:bar",
    section: InsightsSection.Delivery,
    title: "Check status",
    kind: TileKind.CategoryBar,
    dataKey: "checkStatus",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "check-status", label: "Check status" },
    infoKey: "chart:checkStatus",
  }),
  chartTile({
    id: "chart:branchesWithoutPr",
    section: InsightsSection.Delivery,
    title: "Branch coverage",
    kind: TileKind.CategoryBar,
    dataKey: "branchesWithoutPr",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "branch-coverage", label: "Branch coverage" },
    infoKey: "chart:branchesWithoutPr",
  }),
  chartTile({
    id: "chart:branchesWithoutPr:donut",
    section: InsightsSection.Delivery,
    title: "Branch coverage",
    kind: TileKind.Donut,
    dataKey: "branchesWithoutPr",
    metricKey: "merged",
    metricLabel: "Pull requests",
    groupBy: { key: "branch-coverage", label: "Branch coverage" },
    infoKey: "chart:branchesWithoutPr",
  }),
  chartTile({
    id: "chart:meanTimeToMerge",
    section: InsightsSection.Delivery,
    title: "Time to merge",
    kind: TileKind.CategoryBar,
    dataKey: "meanTimeToMerge",
    metricKey: "ttm",
    metricLabel: "Time to merge",
    groupBy: { key: "duration", label: "Duration bucket" },
    infoKey: "chart:meanTimeToMerge",
  }),
  chartTile({
    id: "chart:meanTimeToMerge:donut",
    section: InsightsSection.Delivery,
    title: "Time to merge",
    kind: TileKind.Donut,
    dataKey: "meanTimeToMerge",
    metricKey: "ttm",
    metricLabel: "Time to merge",
    groupBy: { key: "duration", label: "Duration bucket" },
    infoKey: "chart:meanTimeToMerge",
  }),
  chartTile({
    id: "chart:branchLifespan",
    section: InsightsSection.Delivery,
    title: "Branch lifespan",
    kind: TileKind.CategoryBar,
    dataKey: "branchLifespan",
    metricKey: "ttm",
    metricLabel: "Time to merge",
    groupBy: { key: "branch-age", label: "Branch age" },
    infoKey: "chart:branchLifespan",
  }),
  chartTile({
    id: "chart:branchLifespan:donut",
    section: InsightsSection.Delivery,
    title: "Branch lifespan",
    kind: TileKind.Donut,
    dataKey: "branchLifespan",
    metricKey: "ttm",
    metricLabel: "Time to merge",
    groupBy: { key: "branch-age", label: "Branch age" },
    infoKey: "chart:branchLifespan",
  }),

  // Utilization.
  kpiTile(InsightsSection.Utilization, "sessions", "Sessions"),
  kpiTile(InsightsSection.Utilization, "runtime", "Agent runtime"),
  kpiTile(InsightsSection.Utilization, "backlog", "Review backlog"),
  kpiTile(InsightsSection.Utilization, "events", "Events"),
  chartTile({
    id: "chart:eventActivity",
    section: InsightsSection.Utilization,
    title: "Session activity",
    kind: TileKind.TimeSeries,
    dataKey: "eventActivity",
    metricKey: "sessions",
    metricLabel: "Sessions",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventActivity",
    wide: true,
  }),
  chartTile({
    id: "chart:eventActivity:heatmap",
    section: InsightsSection.Utilization,
    title: "Session activity heatmap",
    kind: TileKind.Heatmap,
    dataKey: "eventActivity",
    metricKey: "sessions",
    metricLabel: "Sessions",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventActivity",
    wide: true,
  }),
  chartTile({
    id: "chart:eventActivity:bar",
    section: InsightsSection.Utilization,
    title: "Sessions by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "eventActivity",
    metricKey: "sessions",
    metricLabel: "Sessions",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventActivity",
    wide: true,
  }),
  chartTile({
    id: "chart:eventVolume",
    section: InsightsSection.Utilization,
    title: "Events over time",
    kind: TileKind.TimeSeries,
    dataKey: "eventVolume",
    metricKey: "events",
    metricLabel: "Events",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventVolume",
    wide: true,
  }),
  chartTile({
    id: "chart:eventVolume:bar",
    section: InsightsSection.Utilization,
    title: "Events by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "eventVolume",
    metricKey: "events",
    metricLabel: "Events",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventVolume",
    wide: true,
  }),
  chartTile({
    id: "chart:eventVolume:heatmap",
    section: InsightsSection.Utilization,
    title: "Activity heatmap",
    kind: TileKind.Heatmap,
    dataKey: "eventVolume",
    metricKey: "events",
    metricLabel: "Events",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:eventVolume",
    wide: true,
  }),
  chartTile({
    id: "chart:eventsByType",
    section: InsightsSection.Utilization,
    title: "Events by type",
    kind: TileKind.Donut,
    dataKey: "eventsByType",
    metricKey: "events",
    metricLabel: "Events",
    groupBy: { key: "event-type", label: "Event type" },
    infoKey: "chart:eventsByType",
  }),
  chartTile({
    id: "chart:eventsByType:bar",
    section: InsightsSection.Utilization,
    title: "Events by type",
    kind: TileKind.CategoryBar,
    dataKey: "eventsByType",
    metricKey: "events",
    metricLabel: "Events",
    groupBy: { key: "event-type", label: "Event type" },
    horizontal: true,
    infoKey: "chart:eventsByType",
  }),
  chartTile({
    id: "chart:userBreakdown",
    section: InsightsSection.Utilization,
    title: "Sessions by operator",
    kind: TileKind.CategoryBar,
    dataKey: "userBreakdown",
    metricKey: "sessions",
    metricLabel: "Sessions",
    groupBy: { key: "operator", label: "Operator" },
    horizontal: true,
    infoKey: "chart:userBreakdown",
  }),
  chartTile({
    id: "chart:userBreakdown:donut",
    section: InsightsSection.Utilization,
    title: "Session share by operator",
    kind: TileKind.Donut,
    dataKey: "userBreakdown",
    metricKey: "sessions",
    metricLabel: "Sessions",
    groupBy: { key: "operator", label: "Operator" },
    infoKey: "chart:userBreakdown",
  }),
  chartTile({
    id: "chart:reviewQueue",
    section: InsightsSection.Utilization,
    title: "Review queue",
    kind: TileKind.CategoryBar,
    dataKey: "reviewQueue",
    metricKey: "backlog",
    metricLabel: "Review backlog",
    groupBy: { key: "queue-state", label: "Queue state" },
    infoKey: "chart:reviewQueue",
  }),
  chartTile({
    id: "chart:reviewQueue:donut",
    section: InsightsSection.Utilization,
    title: "Review queue",
    kind: TileKind.Donut,
    dataKey: "reviewQueue",
    metricKey: "backlog",
    metricLabel: "Review backlog",
    groupBy: { key: "queue-state", label: "Queue state" },
    infoKey: "chart:reviewQueue",
  }),
  chartTile({
    id: "chart:reviewerLoad",
    section: InsightsSection.Utilization,
    title: "Reviewer load",
    kind: TileKind.ReviewerTable,
    dataKey: "reviewerLoad",
    metricKey: "backlog",
    metricLabel: "Review backlog",
    groupBy: { key: "reviewer", label: "Reviewer" },
    infoKey: "chart:reviewerLoad",
  }),

  // Agents & tools.
  kpiTile(InsightsSection.Agents, "tokens", "Tokens"),
  kpiTile(InsightsSection.Agents, "input-tokens", "Input tokens"),
  kpiTile(InsightsSection.Agents, "output-tokens", "Output tokens"),
  kpiTile(InsightsSection.Agents, "cache-tokens", "Cache saved"),
  kpiTile(InsightsSection.Agents, "models", "Models in use"),
  kpiTile(InsightsSection.Agents, "tool-runs", "Tool runs"),
  chartTile({
    id: "chart:tokenDistribution",
    section: InsightsSection.Agents,
    title: "Token distribution",
    kind: TileKind.Donut,
    dataKey: "tokenDistribution",
    metricKey: "tokens",
    metricLabel: "Tokens",
    groupBy: { key: "token-type", label: "Token type" },
    infoKey: "chart:tokenDistribution",
  }),
  chartTile({
    id: "chart:tokenDistribution:bar",
    section: InsightsSection.Agents,
    title: "Token distribution",
    kind: TileKind.CategoryBar,
    dataKey: "tokenDistribution",
    metricKey: "tokens",
    metricLabel: "Tokens",
    groupBy: { key: "token-type", label: "Token type" },
    infoKey: "chart:tokenDistribution",
  }),
  chartTile({
    id: "chart:toolUsage",
    section: InsightsSection.Agents,
    title: "Tool usage",
    kind: TileKind.CategoryBar,
    dataKey: "toolUsage",
    metricKey: "tool-runs",
    metricLabel: "Tool runs",
    groupBy: { key: "tool", label: "Tool" },
    horizontal: true,
    infoKey: "chart:toolUsage",
    wide: true,
  }),
  chartTile({
    id: "chart:toolUsage:donut",
    section: InsightsSection.Agents,
    title: "Tool usage share",
    kind: TileKind.Donut,
    dataKey: "toolUsage",
    metricKey: "tool-runs",
    metricLabel: "Tool runs",
    groupBy: { key: "tool", label: "Tool" },
    infoKey: "chart:toolUsage",
  }),
  chartTile({
    id: "chart:agentsByStatus",
    section: InsightsSection.Agents,
    title: "Agents by status",
    kind: TileKind.Donut,
    dataKey: "agentsByStatus",
    metricKey: "tool-runs",
    metricLabel: "Agents",
    groupBy: { key: "status", label: "Status" },
    infoKey: "chart:agentsByStatus",
  }),
  chartTile({
    id: "chart:agentsByStatus:bar",
    section: InsightsSection.Agents,
    title: "Agents by status",
    kind: TileKind.CategoryBar,
    dataKey: "agentsByStatus",
    metricKey: "tool-runs",
    metricLabel: "Agents",
    groupBy: { key: "status", label: "Status" },
    infoKey: "chart:agentsByStatus",
  }),
  chartTile({
    id: "chart:agentsByType",
    section: InsightsSection.Agents,
    title: "Agent type distribution",
    kind: TileKind.CategoryBar,
    dataKey: "agentsByType",
    metricKey: "tool-runs",
    metricLabel: "Agents",
    groupBy: { key: "agent-type", label: "Agent type" },
    horizontal: true,
    infoKey: "chart:agentsByType",
  }),
  chartTile({
    id: "chart:agentsByType:donut",
    section: InsightsSection.Agents,
    title: "Agent type share",
    kind: TileKind.Donut,
    dataKey: "agentsByType",
    metricKey: "tool-runs",
    metricLabel: "Agents",
    groupBy: { key: "agent-type", label: "Agent type" },
    infoKey: "chart:agentsByType",
  }),
  chartTile({
    id: "chart:toolRunsOverTime",
    section: InsightsSection.Agents,
    title: "Tool runs over time",
    kind: TileKind.TimeSeries,
    dataKey: "toolRunsOverTime",
    metricKey: "tool-runs",
    metricLabel: "Tool runs",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:toolRunsOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:toolRunsOverTime:bar",
    section: InsightsSection.Agents,
    title: "Tool runs by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "toolRunsOverTime",
    metricKey: "tool-runs",
    metricLabel: "Tool runs",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:toolRunsOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:toolRunsOverTime:heatmap",
    section: InsightsSection.Agents,
    title: "Tool runs heatmap",
    kind: TileKind.Heatmap,
    dataKey: "toolRunsOverTime",
    metricKey: "tool-runs",
    metricLabel: "Tool runs",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:toolRunsOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:modelUsageOverTime",
    section: InsightsSection.Agents,
    title: "Model spend over time",
    kind: TileKind.TimeSeries,
    dataKey: "modelUsageOverTime",
    metricKey: "cost",
    metricLabel: "Spend",
    groupBy: { key: "model", label: "Model" },
    infoKey: "chart:modelUsageOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:modelUsageOverTime:bar",
    section: InsightsSection.Agents,
    title: "Model spend by day",
    kind: TileKind.TimeSeriesBar,
    dataKey: "modelUsageOverTime",
    metricKey: "cost",
    metricLabel: "Spend",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:modelUsageOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:modelUsageOverTime:heatmap",
    section: InsightsSection.Agents,
    title: "Model spend heatmap",
    kind: TileKind.Heatmap,
    dataKey: "modelUsageOverTime",
    metricKey: "cost",
    metricLabel: "Spend",
    groupBy: { key: "date", label: "Date" },
    infoKey: "chart:modelUsageOverTime",
    wide: true,
  }),
  chartTile({
    id: "chart:modelBreakdown",
    section: InsightsSection.Agents,
    title: "Spend by model",
    kind: TileKind.CategoryBar,
    dataKey: "modelBreakdown",
    metricKey: "cost",
    metricLabel: "Spend",
    groupBy: { key: "model", label: "Model" },
    horizontal: true,
    showValueLabels: true,
    infoKey: "chart:modelBreakdown",
  }),
  chartTile({
    id: "chart:modelBreakdown:models",
    section: InsightsSection.Agents,
    title: "Models in use",
    kind: TileKind.CategoryBar,
    dataKey: "modelBreakdown",
    metricKey: "models",
    metricLabel: "Models in use",
    groupBy: { key: "model", label: "Model" },
    horizontal: true,
    infoKey: "chart:modelBreakdown",
  }),
  chartTile({
    id: "chart:modelBreakdown:donut",
    section: InsightsSection.Agents,
    title: "Spend share by model",
    kind: TileKind.Donut,
    dataKey: "modelBreakdown",
    metricKey: "cost",
    metricLabel: "Spend",
    groupBy: { key: "model", label: "Model" },
    infoKey: "chart:modelBreakdown",
  }),
  chartTile({
    id: "chart:modelBreakdown:models:donut",
    section: InsightsSection.Agents,
    title: "Models in use",
    kind: TileKind.Donut,
    dataKey: "modelBreakdown",
    metricKey: "models",
    metricLabel: "Models in use",
    groupBy: { key: "model", label: "Model" },
    infoKey: "chart:modelBreakdown",
  }),
];

export function getSectionTiles(section: InsightsSection): TileDescriptor[] {
  return INSIGHTS_TILES.filter((tile) => tile.section === section);
}

export function getTile(id: string): TileDescriptor | undefined {
  return INSIGHTS_TILES.find((tile) => tile.id === id);
}

export const REMOVED_DASHBOARD_TILE_IDS = {
  SessionsByStatus: "chart:sessionsByStatus",
  SessionsByStatusBar: "chart:sessionsByStatus:bar",
} as const;

export const DEFAULT_DASHBOARD_TILE_IDS: string[] = [
  "kpi:tokens",
  "kpi:input-tokens",
  "kpi:output-tokens",
  "kpi:cache-tokens",
  "kpi:sessions",
  "kpi:events",
  "kpi:tool-runs",
  "kpi:merged",
  "chart:tokenDistribution",
  "chart:agentsByStatus",
  "chart:eventsByType",
  "chart:eventVolume:heatmap",
  "chart:agentsByType:donut",
  "chart:toolUsage:donut",
  "chart:modelBreakdown:donut",
  "chart:modelUsageOverTime",
  "chart:prTrend",
  "chart:prByRepo",
];
