#!/usr/bin/env bash
# .closedloop-ai/loops-setup.sh — Repository bootstrap for ClosedLoop loop runners.
#
# Executed by the harness agent after git clone, before invoking Claude.
# Runs in a container (node:20-slim / Ubuntu) — do not use brew or macOS tools.
#
# Installs dependencies and configures the environment so that
# build/typecheck/lint commands work without external service credentials.
#
# This script is idempotent — safe to run multiple times.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "[loops-setup] Bootstrapping repository: $REPO_ROOT"

# ---------------------------------------------------------------------------
# 1. Enable corepack and install dependencies
# ---------------------------------------------------------------------------
echo "[loops-setup] Installing dependencies..."
corepack enable 2>/dev/null || true
pnpm install --frozen-lockfile

# ---------------------------------------------------------------------------
# 2. Generate stub .env.local files for each app
#
# The monorepo uses @t3-oss/env-nextjs with Zod validators that require
# specific prefixes (e.g., "phc_", "sk_", "bshb_pk_"). Empty strings fail.
# We generate dummy values that pass validation so builds/typechecks succeed
# without real external service credentials.
#
# NOTE: If you add a new required (non-optional) key to any keys.ts,
# add a matching dummy value here or loops will fail to build.
# ---------------------------------------------------------------------------
generate_env_local() {
  local env_file="$1"
  if [ -f "$env_file" ]; then
    echo "[loops-setup] $env_file already exists, skipping"
    return
  fi
  echo "[loops-setup] Creating $env_file"
  cat > "$env_file" <<'ENVEOF'
# Auto-generated by .closedloop-ai/loops-setup.sh for loop environments.
# Dummy values that pass @t3-oss/env-nextjs Zod validators.
# These are NOT real credentials — they exist only to satisfy build validation.

# payments (required: sk_ prefix)

# github (required: min(1) strings, owner/repo regex)
GITHUB_APP_ID=000000
GITHUB_APP_PRIVATE_KEY=dummy-private-key-for-loops
GITHUB_APP_WEBHOOK_SECRET=dummy-webhook-secret
GITHUB_APP_CLIENT_ID=Iv1.0000000000000000
GITHUB_APP_CLIENT_SECRET=dummy-client-secret-for-loops
GITHUB_APP_DISPATCH_REPO=closedloop-ai/closedloop-ai

# next-config (required: valid URLs)
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_WEB_URL=http://localhost:3001

# api env.ts (required: min(1))
INTERNAL_API_SECRET=dummy-internal-api-secret
ENVEOF
}

for app_dir in apps/app apps/web apps/api; do
  generate_env_local "$app_dir/.env.local"
done

# ---------------------------------------------------------------------------
# 3. Set NODE_OPTIONS for large TypeScript projects
#
# The apps/api typecheck exhausts the default Node.js heap (exit code 137,
# SIGKILL by OOM killer) in 4GB ECS containers. Bump the V8 heap limit.
# ---------------------------------------------------------------------------
export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--max-old-space-size=3072"
echo "[loops-setup] NODE_OPTIONS=$NODE_OPTIONS"

# Persist env vars for the Claude child process.
# The harness agent reads this file before spawning Claude.
cat > "$REPO_ROOT/.closedloop-ai/.env.setup" <<SETUPEOF
export NODE_OPTIONS="$NODE_OPTIONS"
SETUPEOF

# ---------------------------------------------------------------------------
# 4. Generate Prisma client (required before typecheck/build)
# ---------------------------------------------------------------------------
if [ -f packages/database/prisma/schema.prisma ]; then
  echo "[loops-setup] Generating Prisma client..."
  pnpm --filter database exec prisma generate
fi

echo "[loops-setup] Bootstrap complete"
