// Generated by scripts/generate-registry.mjs. Do not edit by hand.
// Regenerate with: pnpm --filter prototypes generate:registry
import { meta as agentsMeta } from "@/app/p/agents/prototype.meta";
import { meta as branchTraceUnavailableMeta } from "@/app/p/branch-trace-unavailable/prototype.meta";
import { meta as branchesMeta } from "@/app/p/branches/prototype.meta";
import { meta as convertInstallFlowMeta } from "@/app/p/convert-install-flow/prototype.meta";
import { meta as desktopDataSyncLevelMeta } from "@/app/p/desktop-data-sync-level/prototype.meta";
import { meta as desktopImportSplashMeta } from "@/app/p/desktop-import-splash/prototype.meta";
import { meta as desktopOnboardingMeta } from "@/app/p/desktop-onboarding/prototype.meta";
import { meta as desktopOnboardingLandingMeta } from "@/app/p/desktop-onboarding-landing/prototype.meta";
import { meta as desktopStartupReadinessMeta } from "@/app/p/desktop-startup-readiness/prototype.meta";
import { meta as desktopSyncSettingsMeta } from "@/app/p/desktop-sync-settings/prototype.meta";
import { meta as desktopUiKitMeta } from "@/app/p/desktop-ui-kit/prototype.meta";
import { meta as documentCommentsMeta } from "@/app/p/document-comments/prototype.meta";
import { meta as genericArtifactMeta } from "@/app/p/generic-artifact/prototype.meta";
import { meta as installMatrixMeta } from "@/app/p/install-matrix/prototype.meta";
import { meta as lostWorkMeta } from "@/app/p/lost-work/prototype.meta";
import { meta as multisessionTraceMeta } from "@/app/p/multisession-trace/prototype.meta";
import { meta as myMachinesMeta } from "@/app/p/my-machines/prototype.meta";
import { meta as packsMeta } from "@/app/p/packs/prototype.meta";
import { meta as packsPageMeta } from "@/app/p/packs-page/prototype.meta";
import { meta as phaseBreakdownMeta } from "@/app/p/phase-breakdown/prototype.meta";
import { meta as postAuthDesktopOnboardingMeta } from "@/app/p/post-auth-desktop-onboarding/prototype.meta";
import { meta as preAuthDesktopOnboardingMeta } from "@/app/p/pre-auth-desktop-onboarding/prototype.meta";
import { meta as prototypesMeta } from "@/app/p/prototypes/prototype.meta";
import { meta as searchResultsMeta } from "@/app/p/search-results/prototype.meta";
import { meta as sessionBranchCommentsMeta } from "@/app/p/session-branch-comments/prototype.meta";
import { meta as sessionSubagentTranscriptsMeta } from "@/app/p/session-subagent-transcripts/prototype.meta";
import { meta as sessionsMeta } from "@/app/p/sessions/prototype.meta";
import { meta as sessionsActiveFiltersMeta } from "@/app/p/sessions-active-filters/prototype.meta";
import { meta as signInMeta } from "@/app/p/sign-in/prototype.meta";
import { meta as tokenopsWasteMeta } from "@/app/p/tokenops-waste/prototype.meta";
import { meta as userProfilePageMeta } from "@/app/p/user-profile-page/prototype.meta";
import { meta as webMasterMeta } from "@/app/p/web-master/prototype.meta";
import { meta as webOnboardingFlowMeta } from "@/app/p/web-onboarding-flow/prototype.meta";
import { meta as webUiKitMeta } from "@/app/p/web-ui-kit/prototype.meta";
import type { PrototypeMeta } from "@/lib/registry";

export const prototypes: readonly PrototypeMeta[] = [
  agentsMeta,
  branchTraceUnavailableMeta,
  branchesMeta,
  convertInstallFlowMeta,
  desktopDataSyncLevelMeta,
  desktopImportSplashMeta,
  desktopOnboardingMeta,
  desktopOnboardingLandingMeta,
  desktopStartupReadinessMeta,
  desktopSyncSettingsMeta,
  desktopUiKitMeta,
  documentCommentsMeta,
  genericArtifactMeta,
  installMatrixMeta,
  lostWorkMeta,
  multisessionTraceMeta,
  myMachinesMeta,
  packsMeta,
  packsPageMeta,
  phaseBreakdownMeta,
  postAuthDesktopOnboardingMeta,
  preAuthDesktopOnboardingMeta,
  prototypesMeta,
  searchResultsMeta,
  sessionBranchCommentsMeta,
  sessionSubagentTranscriptsMeta,
  sessionsMeta,
  sessionsActiveFiltersMeta,
  signInMeta,
  tokenopsWasteMeta,
  userProfilePageMeta,
  webMasterMeta,
  webOnboardingFlowMeta,
  webUiKitMeta,
];
