/**
 * Generates `rds-ca-bundle.ts` from AWS's published RDS CA truststore.
 *
 * The runtime pg pools verify the RDS server certificate against this bundle
 * (merged with the system roots in `db-utils.ts`), because the Amazon RDS CA is
 * not in the Vercel/Node default trust store. The bundle is embedded as a string
 * constant — never fetched at runtime — so DB connectivity never depends on an
 * external HTTP endpoint. This script is the maintenance path: it fetches the
 * canonical AWS source, validates it, pins a SHA-256, and writes the module, so
 * the embedded blob has provenance instead of being hand-pasted.
 *
 * Usage (run from the package root, e.g. via the pnpm scripts):
 *   pnpm --filter @repo/database generate:rds-ca   # regenerate the module
 *   pnpm --filter @repo/database check:rds-ca       # fail if AWS source drifted
 *
 * To narrow to a single region, swap SOURCE_URL for the regional bundle
 * (e.g. .../us-east-1/us-east-1-bundle.pem) and regenerate. The global bundle is
 * used by default so a cross-region endpoint can never reintroduce the
 * self-signed-cert outage this guards against.
 */

import { createHash, X509Certificate } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  RdsCaBundleStatus as PackageRdsCaBundleStatus,
  type RdsCaBundleStatusReport as PackageRdsCaBundleStatusReport,
  type RdsCaBundleStatus as PackageRdsCaBundleStatusType,
} from "./rds-ca-status.js";

export const RdsCaBundleStatus = PackageRdsCaBundleStatus;
export type RdsCaBundleStatus = PackageRdsCaBundleStatusType;
export type RdsCaBundleStatusReport = PackageRdsCaBundleStatusReport;

const SOURCE_URL =
  "https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem";

// Resolved against cwd; the `generate:rds-ca` / `check:rds-ca` pnpm scripts run
// with the package root as cwd.
const OUTPUT_FILE = join(process.cwd(), "scripts", "rds-ca-bundle.ts");
const MODULE_SPECIFIER = "./rds-ca-bundle";

const MIN_EXPECTED_CERTS = 50;
const BACKTICK = String.fromCharCode(96);
const CERT_PATTERN =
  /-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/g;
const RDS_SUBJECT_PATTERN = /Amazon RDS/i;

async function fetchBundle(): Promise<string> {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch RDS CA bundle: HTTP ${res.status} ${res.statusText}`
    );
  }
  return (await res.text()).trim();
}

/**
 * Asserts the fetched PEM is safe to embed and is genuinely the RDS CA bundle.
 * Returns the certificate count.
 */
function validateBundle(pem: string): number {
  if (pem.includes(BACKTICK) || pem.includes("${")) {
    throw new Error(
      "Bundle contains template-literal metacharacters; refusing to embed."
    );
  }
  const certs = pem.match(CERT_PATTERN) ?? [];
  if (certs.length < MIN_EXPECTED_CERTS) {
    throw new Error(
      `Expected at least ${MIN_EXPECTED_CERTS} certificates, parsed ${certs.length}.`
    );
  }
  for (const cert of certs) {
    // Throws on parse failure.
    const parsed = new X509Certificate(cert);
    if (!RDS_SUBJECT_PATTERN.test(parsed.subject)) {
      throw new Error(
        `Non-RDS certificate in bundle: ${parsed.subject.replace(/\n/g, " ")}`
      );
    }
  }
  return certs.length;
}

function sha256(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

function renderModule(pem: string, count: number, digest: string): string {
  return [
    "// AUTO-GENERATED by scripts/generate-rds-ca-bundle.ts — DO NOT EDIT BY HAND.",
    "//",
    "// Amazon RDS public root/intermediate CA bundle (all regions). The runtime",
    "// pg pools verify the RDS server certificate against this bundle (merged with",
    "// the system roots in db-utils.ts) because the RDS CA is not in the Vercel/",
    "// Node default trust store. Embedded as a string constant — not fetched at",
    "// runtime — so DB connectivity never depends on an external HTTP endpoint.",
    "//",
    `// Source:      ${SOURCE_URL}`,
    "// Regenerate:  pnpm --filter @repo/database generate:rds-ca",
    "// Drift check: pnpm --filter @repo/database check:rds-ca",
    "// Integrity:   AWS_RDS_CA_BUNDLE_SHA256 is asserted against the embedded",
    `//              bundle in rds-ca-bundle.test.ts. ${count} certificates.`,
    "",
    `export const AWS_RDS_CA_BUNDLE_SOURCE_URL = ${JSON.stringify(SOURCE_URL)};`,
    "",
    `export const AWS_RDS_CA_BUNDLE_CERT_COUNT = ${count};`,
    "",
    "// SHA-256 of the embedded bundle (trimmed). Pinned so a hand-edit or a",
    "// silent AWS-side change is caught by the unit test and the drift check.",
    `export const AWS_RDS_CA_BUNDLE_SHA256 = ${JSON.stringify(digest)};`,
    "",
    `export const AWS_RDS_CA_BUNDLE = ${BACKTICK}`,
    pem,
    `${BACKTICK};`,
    "",
  ].join("\n");
}

async function check(): Promise<void> {
  const status = await getStatus();
  if (status.status === RdsCaBundleStatus.Match) {
    console.log(
      `OK: embedded RDS CA bundle matches AWS source (${status.certificateCount} certs, sha256 ${status.upstreamSha256}).`
    );
    return;
  }
  if (status.status === RdsCaBundleStatus.Drift) {
    throw new Error(
      `DRIFT: the AWS RDS CA bundle changed.\n  embedded sha256: ${status.embeddedSha256}\n  upstream sha256: ${status.upstreamSha256} (${status.certificateCount} certs)\n  Run: pnpm --filter @repo/database generate:rds-ca`
    );
  }
  throw new Error(status.message);
}

export async function getStatus(
  readEmbeddedSha256ForStatus = readEmbeddedSha256
): Promise<RdsCaBundleStatusReport> {
  let embeddedSha256: string | undefined;
  try {
    embeddedSha256 = await readEmbeddedSha256ForStatus();
    const pem = await fetchBundle();
    const certificateCount = validateBundle(pem);
    const upstreamSha256 = sha256(pem);
    if (upstreamSha256 === embeddedSha256) {
      return {
        certificateCount,
        embeddedSha256,
        message: "Embedded RDS CA bundle matches AWS source.",
        sourceUrl: SOURCE_URL,
        status: RdsCaBundleStatus.Match,
        upstreamSha256,
      };
    }
    return {
      certificateCount,
      embeddedSha256,
      message: "The AWS RDS CA bundle changed.",
      sourceUrl: SOURCE_URL,
      status: RdsCaBundleStatus.Drift,
      upstreamSha256,
    };
  } catch (error) {
    return {
      embeddedSha256,
      message: error instanceof Error ? error.message : String(error),
      sourceUrl: SOURCE_URL,
      status: classifyStatusError(error),
    };
  }
}

async function readEmbeddedSha256(): Promise<string> {
  const bundle = (await import(MODULE_SPECIFIER)) as {
    AWS_RDS_CA_BUNDLE_SHA256: string;
  };
  return bundle.AWS_RDS_CA_BUNDLE_SHA256;
}

export function classifyStatusError(error: unknown): RdsCaBundleStatus {
  const message = error instanceof Error ? error.message : String(error);
  if (message.startsWith("Failed to fetch RDS CA bundle:")) {
    return RdsCaBundleStatus.FetchFailed;
  }
  if (
    message.includes("certificate") ||
    message.includes("template-literal metacharacters")
  ) {
    return RdsCaBundleStatus.InvalidBundle;
  }
  return RdsCaBundleStatus.UnexpectedFailure;
}

function statusExitCode(status: RdsCaBundleStatus): number {
  if (status === RdsCaBundleStatus.Match) {
    return 0;
  }
  if (status === RdsCaBundleStatus.Drift) {
    return 2;
  }
  return 1;
}

async function writeStatusJson(path: string): Promise<RdsCaBundleStatusReport> {
  const status = await getStatus();
  writeFileSync(path, `${JSON.stringify(status, null, 2)}\n`);
  console.log(JSON.stringify(status));
  return status;
}

function readStatusJsonPath(): string | undefined {
  const index = process.argv.indexOf("--status-json");
  if (index === -1) {
    return undefined;
  }
  const path = process.argv[index + 1];
  if (!path) {
    throw new Error("--status-json requires an output path");
  }
  return path;
}

function shouldCheck(): boolean {
  return process.argv.includes("--check");
}

function shouldWriteStatusJson(): boolean {
  return process.argv.includes("--status-json");
}

function shouldRunMain(): boolean {
  return process.argv[1]?.endsWith("generate-rds-ca-bundle.ts") ?? false;
}

async function generate(): Promise<void> {
  const pem = await fetchBundle();
  const count = validateBundle(pem);
  const digest = sha256(pem);
  writeFileSync(OUTPUT_FILE, renderModule(pem, count, digest));
  console.log(`Wrote ${OUTPUT_FILE}\n  certs:  ${count}\n  sha256: ${digest}`);
}

async function main(): Promise<void> {
  const statusJsonPath = readStatusJsonPath();
  if (shouldWriteStatusJson()) {
    if (!statusJsonPath) {
      throw new Error("--status-json requires an output path");
    }
    const status = await writeStatusJson(statusJsonPath);
    process.exit(statusExitCode(status.status));
  }
  if (shouldCheck()) {
    await check();
  } else {
    await generate();
  }
}

if (shouldRunMain()) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
