import type { Appearance } from "@clerk/ui";

/**
 * Shared Clerk appearance overrides for sign-in and sign-up pages.
 * Component-level styles that take precedence over the provider-level config.
 */
export const authPageAppearance: Appearance = {
  options: {
    logoPlacement: "none",
  },
  elements: {
    headerSubtitle: "hidden",
    headerTitle: { fontSize: "1.3rem" },
    card: { boxShadow: "none", border: "none", paddingBottom: 0 },
    cardBox: { boxShadow: "none", border: "none" },
    footer: { background: "var(--background)" },
    formButtonPrimary: {
      background: "var(--primary)",
      color: "var(--primary-foreground)",
      backgroundImage: "none",
      height: "2.5rem",
    },
    main: { gap: "0.9rem" },
    buttonArrowIcon: { display: "none" },
    formButtonPrimary__icon: { display: "none" },
  },
};

/**
 * GitHub-first appearance variant (PRD-532, M7 web row). Establishes the
 * canonical hierarchy from the sign-in prototype
 * (`apps/prototypes/app/p/sign-in`): GitHub is the single filled primary
 * call-to-action, while Google and the email/password path are visually
 * de-emphasized (outline / secondary) so they read as fallbacks rather than
 * peers of GitHub.
 *
 * This is the CODE half of M7 (appearance / emphasis). The complementary
 * provider ordering (which social button renders physically first) is a Clerk
 * Dashboard admin setting and is out of code scope.
 *
 * This is the DEFAULT appearance for the sign-in and sign-up embeds (FEA-4059):
 * it is applied unconditionally. {@link authPageAppearance} remains the shared
 * base these overrides extend, but is no longer the rendered default for the
 * auth pages.
 *
 * Clerk element-key assumptions (verified against `@clerk/ui` 1.6.x):
 * - `socialButtonsBlockButton__<provider>` / `socialButtonsProviderIcon__<provider>`
 *   are provider-scoped selectors generated by Clerk's `IdSelectors` mechanism
 *   (`${element}__${OAuthProvider}`), so `__github` / `__google` are typed-valid
 *   and target the individual social buttons. If Clerk renames these descriptors
 *   in a future major, only the GitHub-first emphasis degrades to Clerk defaults
 *   — the underlying base overrides ({@link authPageAppearance}) are unaffected.
 * - Colors reuse the design-system CSS custom properties (`--primary`,
 *   `--secondary`, `--input`, `--border`, …) rather than hard-coded hex values,
 *   so the variant stays themeable and does not fight the token system.
 */
export const githubFirstAuthPageAppearance: Appearance = {
  ...authPageAppearance,
  elements: {
    ...authPageAppearance.elements,

    // GitHub is the single filled primary CTA: same emphasis the email submit
    // button carried before, now moved onto the GitHub social button.
    socialButtonsBlockButton__github: {
      background: "var(--primary)",
      color: "var(--primary-foreground)",
      backgroundImage: "none",
      borderColor: "transparent",
      height: "2.5rem",
    },
    socialButtonsBlockButtonText__github: {
      color: "var(--primary-foreground)",
      fontWeight: "600",
    },
    socialButtonsProviderIcon__github: {
      filter: "brightness(0) invert(1)",
    },

    // Google is de-emphasized to an outline button (matches the email field's
    // input border/background), so it reads as an alternative rather than a
    // peer of GitHub.
    socialButtonsBlockButton__google: {
      background: "var(--background)",
      color: "var(--foreground)",
      backgroundImage: "none",
      borderColor: "var(--border)",
      height: "2.5rem",
    },
    socialButtonsBlockButtonText__google: {
      color: "var(--foreground)",
      fontWeight: "400",
    },

    // The email/password submit is demoted from filled primary to a secondary
    // button so the email path never competes with GitHub as the primary.
    formButtonPrimary: {
      background: "var(--secondary)",
      color: "var(--secondary-foreground)",
      backgroundImage: "none",
      borderColor: "transparent",
      height: "2.5rem",
    },
    // (`formButtonPrimary__icon: display none` is inherited from the base
    // appearance spread above.)

    // Soften the "or" divider between the primary GitHub CTA and the
    // de-emphasized alternatives bucket.
    dividerRow: { opacity: "0.85" },
    dividerText: { color: "var(--muted-foreground)", fontSize: "0.75rem" },
  },
};

/**
 * Shared appearance for Clerk's *embedded* account surfaces — `<UserProfile>`
 * (Settings → Profile) and `<OrganizationProfile>` (Settings → Organization).
 *
 * FEA-3965 ([VQA] Settings): the embedded Clerk UI shipped its own card chrome
 * and inner navigation rail styled in Clerk's default language, so the Settings
 * surface read as two stacked design systems (our top tab row + Clerk's inner
 * Account rail) with two visual vocabularies. This themes the embed onto the
 * design-system tokens so the seam disappears without restructuring the nav.
 *
 * These surfaces render through `@clerk/nextjs` (clerk-js / Emotion). Clerk only
 * places its own component CSS in a cascade layer when `cssLayerName` is set,
 * and `AuthProvider` leaves it unset, so a plain Tailwind utility-class override
 * on `elements` is not guaranteed to beat Clerk's Emotion rules for the chrome.
 * The overrides that reliably win in this repo — `authPageAppearance`'s
 * `card`/`cardBox` — are Clerk *style objects*, so this config uses style
 * objects too. Every value resolves to a design-system CSS custom property
 * (`var(--primary)`, `var(--border)`, `var(--input)`, `var(--radius)`, …)
 * rather than a hard-coded hex/px, so the embed tracks light/dark theming and
 * DS radius/color changes automatically. Fonts and font weights are already
 * supplied provider-side (`provider.tsx` `variables`), so this config only maps
 * the structural chrome and the inner navigation rail.
 *
 * Consumed by the `apps/app` Settings page only. The desktop renderer has its
 * own `SettingsPanel` / `DesktopAccountTab` and does not embed these Clerk
 * profile surfaces, so this appearance is web-scoped.
 */
export const embeddedProfileAppearance: Appearance = {
  elements: {
    // Fill the tab panel; the DS Card wrapper in the Settings page provides the
    // framing.
    rootBox: { width: "100%" },
    // Drop Clerk's own card chrome so the embed sits flat inside the DS Card
    // wrapper instead of stacking a second bordered card language on top.
    card: {
      boxShadow: "none",
      border: "none",
      background: "transparent",
    },
    cardBox: {
      boxShadow: "none",
      border: "none",
      background: "transparent",
    },
    // The inner Account/Profile/Security rail is the "second navigation" the
    // VQA flagged. Style it to read as part of the app: keep the right-edge
    // divider between the rail and the content, but paint it with the DS border
    // token plus foreground text + muted hover so it looks like one system
    // rather than a Clerk widget bolted on.
    navbar: {
      borderRight: "1px solid var(--border)",
    },
    navbarButton: {
      color: "var(--foreground)",
      "&:hover": { background: "var(--muted)" },
    },
    // The selected rail item mirrors our TabsTrigger active treatment
    // (`data-[state=active]:bg-muted text-accent-foreground`) so the current
    // page reads the same way in both navigation levels.
    navbarButton__active: {
      background: "var(--muted)",
      color: "var(--accent-foreground)",
    },
    navbarButtonIcon: {
      color: "var(--muted-foreground)",
    },
    // Match the DS Input recipe (`bg-input border-input-border` with a
    // `focus-visible` ring on `--ring`) so the embed's fields read identically
    // to the native DS Input that sits right beside them in the Organization
    // tab, including in dark mode.
    formFieldInput: {
      background: "var(--input)",
      borderColor: "var(--input-border)",
      borderRadius: "var(--radius)",
      "&:focus": {
        borderColor: "var(--ring)",
        boxShadow:
          "0 0 0 3px color-mix(in oklab, var(--ring) 50%, transparent)",
      },
    },
    // The one filled primary action inside the embed is Clerk's own form submit
    // (Save). The small profile-section actions (`+ Add email`, `Set as
    // primary`, …) are demoted to a quiet secondary treatment so the surface has
    // a single primary and a clear hierarchy rather than a column of filled
    // buttons.
    formButtonPrimary: {
      background: "var(--primary)",
      color: "var(--primary-foreground)",
      backgroundImage: "none",
    },
    profileSectionPrimaryButton: {
      background: "transparent",
      color: "var(--foreground)",
      backgroundImage: "none",
      "&:hover": { background: "var(--muted)" },
    },
    // Match the DS `muted` Badge variant: pill radius, small text, muted fill on
    // the DS border token.
    badge: {
      background: "color-mix(in oklab, var(--muted) 70%, transparent)",
      color: "var(--muted-foreground)",
      borderColor: "var(--border)",
      borderRadius: "9999px",
      fontSize: "0.75rem",
    },
    // The org-members invite action stays the filled primary CTA.
    membersPageInviteButton: {
      background: "var(--primary)",
      color: "var(--primary-foreground)",
      backgroundImage: "none",
    },
  },
};

/**
 * Embedded-profile appearance for `<OrganizationProfile>`. Extends
 * {@link embeddedProfileAppearance} and hides Clerk's native slug field because
 * we manage the org slug through our own `OrganizationSlugEditor`. These keys
 * are typed in `@clerk/types`; a SDK upgrade that renames them surfaces as a
 * type error rather than silently un-hiding the field.
 */
export const embeddedOrganizationProfileAppearance: Appearance = {
  elements: {
    ...embeddedProfileAppearance.elements,
    formField__slug: { display: "none" },
    formFieldLabel__slug: { display: "none" },
  },
};
