/**
 * PLN-1389 Phase 2 — Golden web-sync parity test (PRD-522 R5), flagship.
 *
 * Proves the one drift class the desktop-local golden layers structurally cannot
 * see: sync -> cloud (apps/api Postgres) persistence -> org-scoped cloud read. A
 * frozen golden session's PRODUCTION-BUILT sync payload (Phase 1 derived fixture)
 * is ingested through the real cloud ingress contract + upsert, then read back
 * through the cloud read services and asserted equal to the dossier's oracle
 * `expectations.yaml`.
 *
 * The derived payload is generated by production code (write-core importer +
 * sync-source), so this test contains NO bespoke golden->payload mapping — the
 * assertion sits directly between the oracle and the cloud read.
 *
 * Scope (R5.1–R5.4): session/token/turn facts + branch-rollup behaviour. It runs
 * ALONGSIDE, not instead of, the desktop-local golden layers. Full branch-rollup
 * SUM parity needs a repo-resolving fixture (the Phase 0 cross-surface scenario);
 * golden import resolves no repository hermetically, so the branch fact this test
 * can assert is the negative: the cloud must not fabricate a branch the desktop
 * never sent.
 */
import { AgentSessionSyncMode } from "@repo/api/src/types/agent-session";
import { DISPLAYED_SESSION_STATUS } from "@repo/api/src/types/session-status";
import { withDb } from "@repo/database";
import { keys } from "@repo/database/keys";
import { describe, expect, it } from "vitest";
import {
  autoRollbackTransaction,
  createTestOrganization,
  createTestUser,
} from "@/__tests__/utils/db-helpers";
import {
  loadDerivedSyncFixture,
  loadGoldenExpectations,
} from "@/__tests__/utils/golden-web-sync-fixture";
import { agentSessionsService } from "@/app/agent-sessions/service";
import { branchReadService } from "@/app/branches/branch-read-service";
import { parseDesktopAgentSessionsPayload } from "@/lib/desktop-agent-sessions-schema";

const hasDatabase = Boolean(keys().DATABASE_URL);
const describeIfDb = hasDatabase ? describe : describe.skip;

// v1 dossier: smallest priced single-model claude session with real cache tokens
// (PLN-1389 Phase 1.2). Add more entries here as further dossiers are frozen.
const GOLDEN_DOSSIER_IDS = ["f9830b64-52fb-47c7-a115-07fc17372bb5"] as const;

// Fixed, valid UUID for the ingest batch envelope — a per-batch concern the test
// owns (kept out of the byte-stable derived fixture).
const TEST_BATCH_ID = "00000000-0000-4000-8000-000000000001";

// ISS-5592: what the cloud now READS BACK for a retired oracle spelling. The
// ingest no longer folds `completed`/`abandoned` — they are unrecognized, so the
// fail-open branch stores `active` — and this dossier's activity is older than
// the 24h display cutoff, so the read projects `stale`.
//
// Two things worth naming, because this used to be `inactive`:
//   1. The golden session is FINISHED. It now reads as a live-but-silent run.
//      That is the accepted cost of removing the tolerance, made visible on real
//      corpus data rather than argued in the abstract.
//   2. This expectation is CLOCK-COUPLED in a way the old one was not. `inactive`
//      is terminal and exempt from the staleness fold; `active` is not. The
//      dossier is frozen in the past so the value is stable today, but a future
//      change to the staleness cutoff moves this assertion.
//
// Still spelled here rather than routed through the fold, so a regression moves
// only ONE side of the assertion.
const RETIRED_STATUS_READS_BACK_AS: Partial<Record<string, string>> = {
  completed: DISPLAYED_SESSION_STATUS.STALE,
  abandoned: DISPLAYED_SESSION_STATUS.STALE,
};

async function createComputeTarget(
  organizationId: string,
  userId: string
): Promise<string> {
  const target = await withDb((db) =>
    db.computeTarget.create({
      data: {
        organizationId,
        userId,
        machineName: "golden-web-sync",
        platform: "darwin",
      },
      select: { id: true },
    })
  );
  return target.id;
}

describeIfDb("golden web-sync parity (PRD-522 R5)", () => {
  for (const sessionId of GOLDEN_DOSSIER_IDS) {
    it(`ingests the derived payload for ${sessionId} and reads back == expectations.yaml`, async () => {
      await autoRollbackTransaction(async () => {
        const oracle = loadGoldenExpectations(sessionId);
        const fixture = loadDerivedSyncFixture(sessionId);

        // ── seed org / user / compute target ──────────────────────────────
        const organizationId = await createTestOrganization();
        const user = await createTestUser(organizationId);
        const computeTargetId = await createComputeTarget(
          organizationId,
          user.id
        );

        // ── validate against the REAL cloud ingress contract, then ingest ──
        const parsed = parseDesktopAgentSessionsPayload({
          schemaVersion: fixture.schemaVersion,
          batchId: TEST_BATCH_ID,
          syncMode: AgentSessionSyncMode.Backfill,
          sessionCount: fixture.sessions.length,
          sessions: fixture.sessions,
        });
        expect(
          parsed.ok,
          parsed.ok
            ? ""
            : `derived payload failed the cloud ingress contract: ${parsed.reason}`
        ).toBe(true);
        if (!parsed.ok) {
          return;
        }
        await agentSessionsService.upsertSessions(
          { organizationId, userId: user.id, computeTargetId },
          parsed.payload
        );

        // ── resolve the cloud session artifact id ─────────────────────────
        const externalSessionId = fixture.sessions[0].externalSessionId;
        const { artifactId } = await withDb((db) =>
          db.sessionDetail.findUniqueOrThrow({
            where: {
              computeTargetId_externalSessionId: {
                computeTargetId,
                externalSessionId,
              },
            },
            select: { artifactId: true },
          })
        );

        // ── read back through the CLOUD path ──────────────────────────────
        const detail = await agentSessionsService.findSessionDetail({
          organizationId,
          id: artifactId,
        });
        expect(detail).not.toBeNull();
        if (!detail) {
          return;
        }

        // (1) session facts (R5.1). We assert every oracle field the cloud detail
        // read actually surfaces: status, harness, primary_model, models_used.
        // Deliberately NOT asserted (no faithful cloud-read equivalent, so they
        // could not detect drift here): `turns.total`/`turns.tool_result` — the
        // cloud has no distinct tool_result turn count (see (3)); `cost`/
        // `billing_mode` — the golden oracle zeroes cost by convention while the
        // synced payload carries a real computed cost, so cost is not a golden
        // parity axis, and billingMode is not exposed by AgentSessionDetail;
        // `lifecycle`/`pr_lifecycle` — not surfaced as cloud-read fields for this
        // repo-unresolved, PR-less dossier. A repo/PR-bearing synthetic fixture
        // (Phase 0) is where cost/PR/lifecycle parity is exercised.
        // The oracle records the desktop truth verbatim; the cloud deliberately
        // stores the ISS-5648 persist fold of it (retired spellings land as
        // `inactive`), so the parity axis is the folded oracle, identity for
        // non-retired statuses. The mapping is spelled here rather than routed
        // through `normalizeSessionStatus` so a fold regression
        // moves only ONE side of this assertion instead of both.
        const expectedStatus = RETIRED_STATUS_READS_BACK_AS[oracle.status];
        expect(detail.status).toBe(expectedStatus ?? oracle.status);
        expect(detail.harness).toBe(oracle.harness);
        expect(detail.primaryModel).toBe(oracle.primaryModel);
        expect([...(detail.models ?? [])].sort()).toEqual(
          [...oracle.modelsUsed].sort()
        );

        // (2) tokens_by_model — FLAGSHIP: the sync/serialization drift class the
        // local-only golden layers cannot see (R5.3). Exact per-model counts.
        const cloudByModel = new Map(
          detail.tokenUsageByModel.map((usage) => [usage.model, usage])
        );
        expect([...cloudByModel.keys()].sort()).toEqual(
          Object.keys(oracle.tokensByModel).sort()
        );
        for (const [model, expected] of Object.entries(oracle.tokensByModel)) {
          const got = cloudByModel.get(model);
          expect(got, `no cloud token usage for model ${model}`).toBeDefined();
          if (!got) {
            continue;
          }
          expect(got.inputTokens, `${model} input`).toBe(expected.input);
          expect(got.outputTokens, `${model} output`).toBe(expected.output);
          expect(got.cacheReadTokens, `${model} cache_read`).toBe(
            expected.cacheRead
          );
          expect(got.cacheWriteTokens, `${model} cache_write`).toBe(
            expected.cacheWrite
          );
        }

        // (3) turn counts via the analytics rollup (R5.1). humanTurns/agentTurns
        // map to oracle user/assistant. The session-level `turns` count excludes
        // tool_result (cloud has no distinct tool_result turn), so it equals
        // user + assistant, not the oracle's total.
        const analytics = await agentSessionsService.getSessionAnalytics({
          organizationId,
          sessionArtifactId: artifactId,
        });
        expect(analytics).not.toBeNull();
        expect(analytics?.humanTurns).toBe(oracle.turns.user);
        expect(analytics?.agentTurns).toBe(oracle.turns.assistant);
        expect(detail.turns).toBe(oracle.turns.user + oracle.turns.assistant);

        // (4) branch-rollup fact (R5) — negative parity: a golden session whose
        // repository does not resolve carries no branch link, so the org-scoped
        // cloud branch read must not fabricate one for it (matches the desktop
        // -local read). Full SUM parity is covered by the Phase 0 synthetic
        // repo-bearing fixture, out of this test's scope.
        const branches = await branchReadService.listBranches(organizationId, {
          limit: 50,
          offset: 0,
        });
        const linkedToSession = branches.items.filter((branch) =>
          branch.sessionIds.includes(artifactId)
        );
        expect(linkedToSession).toEqual([]);
      });
    });
  }
});
