/**
 * Bootstrap regression tests — agents-supersede (T-21.5c, AC-027, AC-028).
 *
 * These are unit tests for `bulkIngestAgents` from `@/app/catalog/service`,
 * which is called by `ingestBootstrapAgents` inside `loop-orchestrator.ts`
 * after the agents-supersede migration.
 *
 * Covered:
 * - New agents → CatalogItem + CatalogItemVersion created (version=1, changeNote)
 * - Existing agents (same role+sourceRepo) → version incremented, new
 *   CatalogItemVersion with changeNote='Re-generated by bootstrap'
 * - Duplicate roles within a batch are deduped (last-wins)
 * - RepoBootstrapConfig upserted when criticGates is present
 * - RepoBootstrapConfig NOT upserted when criticGates is absent
 * - Result shape: {created, updated, items}
 *
 * @repo/database is mocked — no live DB required.
 */

import { describe, expect, it, type Mock, vi } from "vitest";

vi.mock("@repo/database", () => ({
  withDb: vi.fn(),
}));

import { withDb } from "@repo/database";
import { bulkIngestAgents } from "@/app/catalog/service";

const mockWithDb = withDb as unknown as Mock & { tx: Mock };

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type ExistingItem = {
  id: string;
  role: string | null;
  name: string;
  versions: Array<{ version: number }>;
};

type MockTxClient = {
  catalogItem: {
    findMany: ReturnType<typeof vi.fn>;
    // Used by generateUniqueAgentSlug to check for slug collisions (FEA-2923).
    findFirst: ReturnType<typeof vi.fn>;
    create: ReturnType<typeof vi.fn>;
    update: ReturnType<typeof vi.fn>;
  };
  catalogItemVersion: {
    create: ReturnType<typeof vi.fn>;
  };
  repoBootstrapConfig: {
    upsert: ReturnType<typeof vi.fn>;
  };
  // FEA-2923 (Gap A, forward path): createNewItem materializes an
  // agent_components row on the org's cloud sentinel compute target, so the
  // mock tx must expose these models even for tests that don't assert on them.
  computeTarget: {
    findFirst: ReturnType<typeof vi.fn>;
    create: ReturnType<typeof vi.fn>;
  };
  user: {
    findFirst: ReturnType<typeof vi.fn>;
  };
  agentComponent: {
    upsert: ReturnType<typeof vi.fn>;
  };
};

/** Build a mock transaction client. */
function buildMockTx(existing: ExistingItem[] = []): MockTxClient {
  return {
    catalogItem: {
      findMany: vi.fn().mockResolvedValue(existing),
      // Default: no existing agentSlug collision → generateUniqueAgentSlug
      // returns the base slug unchanged.
      findFirst: vi.fn().mockResolvedValue(null),
      create: vi
        .fn()
        .mockImplementation((args: { data: Record<string, unknown> }) =>
          Promise.resolve({
            id: "new-item-id",
            role: args.data.role ?? null,
            name: args.data.name,
          })
        ),
      update: vi.fn().mockResolvedValue({}),
    },
    catalogItemVersion: {
      create: vi.fn().mockResolvedValue({}),
    },
    repoBootstrapConfig: {
      upsert: vi.fn().mockResolvedValue({}),
    },
    // Forward-path materialization: no sentinel yet → one is created and owned
    // by the org's earliest active user; the agent_components upsert succeeds.
    computeTarget: {
      findFirst: vi.fn().mockResolvedValue(null),
      create: vi.fn().mockResolvedValue({ id: "cloud-sentinel-1" }),
    },
    user: {
      findFirst: vi.fn().mockResolvedValue({ id: "earliest-user-1" }),
    },
    agentComponent: {
      upsert: vi.fn().mockResolvedValue({}),
    },
  };
}

/**
 * Wire up `withDb.tx` to invoke the callback with the given mock transaction.
 */
function setupTx(mockTx: MockTxClient): void {
  mockWithDb.tx = vi
    .fn()
    .mockImplementation((callback: (tx: unknown) => unknown) =>
      callback(mockTx)
    );
}

// ---------------------------------------------------------------------------
// New agent creation
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — new agent creation", () => {
  it("creates a CatalogItem with correct fields for a new agent", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        {
          name: "Code Reviewer",
          role: "code-reviewer",
          description: "Reviews code",
          prompt: "You are a code reviewer.",
        },
      ],
      bootstrapRunId: "loop-bootstrap-1",
      sourceRepo: "owner/repo-a",
    });

    expect(mockTx.catalogItem.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          organizationId: "org-1",
          targetKind: "agent",
          source: "org_custom",
          scope: "org",
          name: "Code Reviewer",
          role: "code-reviewer",
          sourceRepo: "owner/repo-a",
          // Persisted, disambiguated context-pack slug (FEA-2923).
          agentSlug: "code-reviewer",
          sourceLoopId: "loop-bootstrap-1",
          createdById: "user-1",
        }),
      })
    );
  });

  it("persists a -2-suffixed agentSlug when the base slug already exists for the org (same-role collision)", async () => {
    const mockTx = buildMockTx([]);
    // First slug probe (base) hits an existing row; the -2 candidate is free.
    mockTx.catalogItem.findFirst
      .mockResolvedValueOnce({ id: "existing-code-reviewer" })
      .mockResolvedValueOnce(null);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        {
          name: "Code Reviewer (repo)",
          role: "code-reviewer",
          prompt: "Repo-specific reviewer.",
        },
      ],
      bootstrapRunId: "loop-bootstrap-2",
      sourceRepo: "owner/repo-b",
    });

    expect(mockTx.catalogItem.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ agentSlug: "code-reviewer-2" }),
      })
    );
  });

  it("creates a CatalogItemVersion with version=1 and initial changeNote", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        {
          name: "Test Agent",
          role: "test-agent",
          prompt: "Do testing.",
        },
      ],
      bootstrapRunId: "loop-1",
      sourceRepo: "",
    });

    expect(mockTx.catalogItemVersion.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          version: 1,
          name: "Test Agent",
          content: "Do testing.",
          changeNote: "Initial version from bootstrap",
          changedById: "user-1",
        }),
      })
    );
  });

  it("reports created count in the result", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    const result = await bulkIngestAgents("org-1", "user-1", {
      agents: [
        { name: "Agent A", role: "agent-a", prompt: "Prompt A." },
        { name: "Agent B", role: "agent-b", prompt: "Prompt B." },
      ],
      bootstrapRunId: "loop-1",
      sourceRepo: "owner/repo",
    });

    expect(result.created).toBe(2);
    expect(result.updated).toBe(0);
    expect(result.items).toHaveLength(2);
  });
});

// ---------------------------------------------------------------------------
// Existing agent update (version increment)
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — existing agent update", () => {
  it("does NOT call catalogItem.create for an existing role+sourceRepo", async () => {
    const existing: ExistingItem[] = [
      {
        id: "existing-id",
        role: "code-reviewer",
        name: "Code Reviewer",
        versions: [{ version: 1 }],
      },
    ];
    const mockTx = buildMockTx(existing);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        {
          name: "Code Reviewer v2",
          role: "code-reviewer",
          prompt: "Updated prompt.",
        },
      ],
      bootstrapRunId: "loop-2",
      sourceRepo: "owner/repo",
    });

    expect(mockTx.catalogItem.create).not.toHaveBeenCalled();
  });

  it("calls catalogItem.update for an existing item", async () => {
    const existing: ExistingItem[] = [
      {
        id: "existing-id",
        role: "security-auditor",
        name: "Security Auditor",
        versions: [{ version: 2 }],
      },
    ];
    const mockTx = buildMockTx(existing);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        {
          name: "Security Auditor v3",
          role: "security-auditor",
          prompt: "Audit harder.",
        },
      ],
      bootstrapRunId: "loop-3",
      sourceRepo: "owner/repo",
    });

    expect(mockTx.catalogItem.update).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { id: "existing-id" },
      })
    );
  });

  it("creates a new CatalogItemVersion with incremented version and re-bootstrap changeNote", async () => {
    const existing: ExistingItem[] = [
      {
        id: "existing-id",
        role: "helper",
        name: "Helper",
        versions: [{ version: 3 }],
      },
    ];
    const mockTx = buildMockTx(existing);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        { name: "Helper v4", role: "helper", prompt: "New helper prompt." },
      ],
      bootstrapRunId: "loop-4",
      sourceRepo: "owner/repo",
    });

    expect(mockTx.catalogItemVersion.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          version: 4, // 3 + 1
          changeNote: "Re-generated by bootstrap",
          content: "New helper prompt.",
          changedById: "user-1",
        }),
      })
    );
  });

  it("reports updated count in the result", async () => {
    const existing: ExistingItem[] = [
      {
        id: "item-a",
        role: "agent-a",
        name: "Agent A",
        versions: [{ version: 1 }],
      },
    ];
    const mockTx = buildMockTx(existing);
    setupTx(mockTx);

    const result = await bulkIngestAgents("org-1", "user-1", {
      agents: [
        { name: "Agent A updated", role: "agent-a", prompt: "Updated." },
      ],
      bootstrapRunId: "loop-2",
      sourceRepo: "owner/repo",
    });

    expect(result.updated).toBe(1);
    expect(result.created).toBe(0);
    expect(result.items).toHaveLength(1);
  });
});

// ---------------------------------------------------------------------------
// Dedup by role (last-wins within the batch)
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — dedup by role within batch", () => {
  it("deduplicates duplicate roles in the input batch (last-wins)", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [
        { name: "Agent First", role: "my-agent", prompt: "First prompt." },
        { name: "Agent Last", role: "my-agent", prompt: "Last prompt." },
      ],
      bootstrapRunId: "loop-1",
      sourceRepo: "owner/repo",
    });

    // Only one create call: the second (last-wins) entry for role=my-agent
    expect(mockTx.catalogItem.create).toHaveBeenCalledTimes(1);
    expect(mockTx.catalogItemVersion.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          content: "Last prompt.",
          name: "Agent Last",
        }),
      })
    );
  });
});

// ---------------------------------------------------------------------------
// RepoBootstrapConfig upsert (criticGates)
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — RepoBootstrapConfig upsert", () => {
  it("upserts RepoBootstrapConfig when criticGates is provided", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    const gates = { security: true, performance: false };

    await bulkIngestAgents("org-1", "user-1", {
      agents: [{ name: "Agent A", role: "agent-a", prompt: "Prompt." }],
      bootstrapRunId: "loop-5",
      sourceRepo: "owner/repo-x",
      criticGates: gates,
    });

    expect(mockTx.repoBootstrapConfig.upsert).toHaveBeenCalledWith(
      expect.objectContaining({
        where: {
          organizationId_repoFullName: {
            organizationId: "org-1",
            repoFullName: "owner/repo-x",
          },
        },
        create: expect.objectContaining({
          organizationId: "org-1",
          repoFullName: "owner/repo-x",
          criticGates: gates,
          bootstrapRunId: "loop-5",
        }),
        update: expect.objectContaining({
          criticGates: gates,
          bootstrapRunId: "loop-5",
        }),
      })
    );
  });

  it("does NOT upsert RepoBootstrapConfig when criticGates is absent", async () => {
    const mockTx = buildMockTx([]);
    setupTx(mockTx);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [{ name: "Agent B", role: "agent-b", prompt: "Prompt." }],
      bootstrapRunId: "loop-6",
      sourceRepo: "owner/repo-y",
    });

    expect(mockTx.repoBootstrapConfig.upsert).not.toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// Idempotency: second call for same agent increments version, not duplicate row
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — idempotency on second ingest", () => {
  it("on second call: increments version to 2 and does not create a duplicate CatalogItem", async () => {
    // First call: item does not exist
    const mockTxFirst = buildMockTx([]);
    setupTx(mockTxFirst);

    await bulkIngestAgents("org-1", "user-1", {
      agents: [{ name: "My Agent", role: "my-agent", prompt: "v1 prompt." }],
      bootstrapRunId: "loop-1",
      sourceRepo: "owner/repo",
    });

    // Second call: item exists with version=1
    const existingAfterFirst: ExistingItem[] = [
      {
        id: "item-created",
        role: "my-agent",
        name: "My Agent",
        versions: [{ version: 1 }],
      },
    ];
    const mockTxSecond = buildMockTx(existingAfterFirst);
    setupTx(mockTxSecond);

    const secondResult = await bulkIngestAgents("org-1", "user-1", {
      agents: [{ name: "My Agent", role: "my-agent", prompt: "v2 prompt." }],
      bootstrapRunId: "loop-2",
      sourceRepo: "owner/repo",
    });

    // Second call should update (not create) the CatalogItem
    expect(mockTxSecond.catalogItem.create).not.toHaveBeenCalled();
    expect(mockTxSecond.catalogItem.update).toHaveBeenCalledTimes(1);
    expect(mockTxSecond.catalogItemVersion.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          version: 2,
          content: "v2 prompt.",
        }),
      })
    );
    expect(secondResult.updated).toBe(1);
    expect(secondResult.created).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Version-race retry
// ---------------------------------------------------------------------------

describe("bulkIngestAgents — version-race retry", () => {
  it("retries the whole ingest transaction on a P2002 version collision", async () => {
    const existing: ExistingItem[] = [
      {
        id: "existing-id",
        role: "code-reviewer",
        name: "Code Reviewer",
        versions: [{ version: 1 }],
      },
    ];

    // First transaction: a concurrent bootstrap already claimed version 2, so
    // the version create trips the unique(catalogItemId, version) index.
    const failingTx = buildMockTx(existing);
    failingTx.catalogItemVersion.create.mockRejectedValueOnce(
      Object.assign(new Error("Unique constraint failed"), { code: "P2002" })
    );

    // Retry transaction: max(version) has advanced; the ingest succeeds.
    const succeedingTx = buildMockTx([
      {
        id: "existing-id",
        role: "code-reviewer",
        name: "Code Reviewer",
        versions: [{ version: 2 }],
      },
    ]);

    mockWithDb.tx = vi
      .fn()
      .mockImplementationOnce((callback: (tx: unknown) => unknown) =>
        callback(failingTx)
      )
      .mockImplementationOnce((callback: (tx: unknown) => unknown) =>
        callback(succeedingTx)
      );

    const result = await bulkIngestAgents("org-1", "user-1", {
      agents: [
        { name: "Code Reviewer v2", role: "code-reviewer", prompt: "v2." },
      ],
      bootstrapRunId: "loop-2",
      sourceRepo: "owner/repo",
    });

    // Two transaction attempts: the collision, then the successful retry.
    expect(mockWithDb.tx).toHaveBeenCalledTimes(2);
    // On retry, the re-read max(version) advanced to 2 → claims version 3.
    expect(succeedingTx.catalogItemVersion.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ version: 3, content: "v2." }),
      })
    );
    expect(result.updated).toBe(1);
  });

  it("rethrows non-P2002 errors without retrying", async () => {
    const mockTx = buildMockTx([]);
    mockTx.catalogItem.create.mockRejectedValueOnce(
      Object.assign(new Error("connection reset"), { code: "P1001" })
    );
    mockWithDb.tx = vi
      .fn()
      .mockImplementation((callback: (tx: unknown) => unknown) =>
        callback(mockTx)
      );

    await expect(
      bulkIngestAgents("org-1", "user-1", {
        agents: [{ name: "New", role: "new-role", prompt: "p." }],
        bootstrapRunId: "loop-9",
        sourceRepo: "owner/repo",
      })
    ).rejects.toThrow("connection reset");

    // No retry on a non-collision error.
    expect(mockWithDb.tx).toHaveBeenCalledTimes(1);
  });
});
