/**
 * Main-process Docs & Help service (FEA-3843 / PRD-555 M1).
 *
 * Wraps the build-time {@link DocsBundle} snapshot with the three read-only
 * operations the `docs-help` IPC exposes: `search` (over the local index),
 * `getPage` (by bundle path), and `status` (version stamp + availability). The
 * bundle and index live entirely in the main process; the renderer queries via
 * `window.desktopApi.docsHelp.*` (wired in M2/FEA-3844).
 *
 * The generated `docs-bundle-manifest.ts` is gitignored and produced by
 * `pnpm prebuild` (see `scripts/generate-docs-bundle-manifest.mjs`). This module
 * takes the bundle by injection so it stays unit-testable without the generated
 * file; `loadDocsHelpService()` is the production entrypoint that reads the
 * manifest.
 */
import type {
  DocsHelpGetPageResult,
  DocsHelpNavGroup,
  DocsHelpNavResult,
  DocsHelpSearchResult,
  DocsHelpStatus,
} from "../../shared/docs-help-contract.js";
import { DOCS_BUNDLE } from "./docs-bundle-manifest.js";
import type { DocsBundle } from "./docs-bundle-types.js";
import { buildDocsNavTree } from "./docs-nav-tree.js";
import {
  buildDocsSearchIndex,
  type DocsSearchIndex,
} from "./docs-search-index.js";

export type DocsHelpService = {
  search: (query: string, limit?: number) => DocsHelpSearchResult;
  getPage: (path: string) => DocsHelpGetPageResult;
  status: () => DocsHelpStatus;
  /** The `meta.json` nav tree (groups → pages) for the M2 Help view's left pane. */
  nav: () => DocsHelpNavResult;
};

/**
 * Build a Docs & Help service over an in-memory bundle. Pure — no filesystem,
 * no Electron. The IPC handler and tests both construct through here.
 */
export function createDocsHelpService(bundle: DocsBundle): DocsHelpService {
  const index: DocsSearchIndex = buildDocsSearchIndex(bundle);
  const pagesByPath = new Map(bundle.pages.map((page) => [page.path, page]));
  const available = bundle.pages.length > 0;
  // The nav tree is a pure function of the (immutable) bundle, so build it once.
  const navGroups: readonly DocsHelpNavGroup[] = buildDocsNavTree(
    bundle.pages.map((page) => ({
      path: page.path,
      title: page.title,
      ...(page.group ? { group: page.group } : {}),
    }))
  );

  const search = (query: string, limit?: number): DocsHelpSearchResult => ({
    query,
    hits: index.search(query, limit),
  });

  const getPage = (path: string): DocsHelpGetPageResult => {
    const page = pagesByPath.get(path);
    return page ? { kind: "found", page } : { kind: "missing" };
  };

  const status = (): DocsHelpStatus => ({
    available,
    sourceCommit: bundle.sourceCommit,
    generatedAt: bundle.generatedAt,
    pageCount: bundle.pages.length,
    docsSiteUrl: bundle.docsSiteUrl,
  });

  const nav = (): DocsHelpNavResult => ({ groups: navGroups });

  return { search, getPage, status, nav };
}

/**
 * Production entrypoint: build the service over the build-time bundle manifest
 * (generated by `pnpm prebuild`, embedded in `dist/` for packaging). When the
 * manifest is empty (its generator found no docs), `createDocsHelpService`
 * already reports `available: false`, so the Help surfaces stay dark — matching
 * the flag-off / no-bundle contract without a separate fallback path.
 */
export function loadDocsHelpService(): DocsHelpService {
  return createDocsHelpService(DOCS_BUNDLE);
}
