import {
  CollectorProductSignalAttributeKeys,
  TelemetryAttribute,
} from "../src/attributes";
import {
  assertYamlSafeKeys,
  writeGeneratedArtifact,
} from "./collector-codegen-common";

/**
 * Codegen (FEA-1991, PRD-481 C3): emit the keyless-telemetry Collector's
 * PostHog-routing `filter` fragment from the contract's product-signal marker
 * SSOT (via {@link CollectorProductSignalAttributeKeys}).
 *
 * Two committed artifacts are produced — a machine-readable JSON manifest and a
 * ready-to-vendor otelcol `filter/product_signals` processor fragment. The
 * cl-tofu collector config vendors the fragment into a `traces/posthog` pipeline
 * (`[resource, redaction, filter/product_signals, batch] -> [otlphttp/posthog]`)
 * so designated product signals (GenAI generations) fan out to PostHog alongside
 * the Datadog ops leg. The drift guard (`check-collector-posthog-routing.ts`)
 * re-runs this rendering in memory and fails the build if the committed copies
 * are stale or diverge from the contract. The rendering is a pure function of
 * the marker set, so the artifacts only change when the markers change — not on
 * unrelated package version bumps.
 */

export const CollectorPosthogRoutingPath = {
  Manifest: "collector/posthog-product-signals.json",
  Fragment: "collector/keyless-telemetry-posthog-routing.yaml",
} as const;

export const CollectorPosthogIdentityPath = {
  Manifest: "collector/posthog-identity-transform.json",
  Fragment: "collector/keyless-telemetry-posthog-identity.yaml",
} as const;

/**
 * The otelcol processor name emitted by (and asserted against) the routing
 * fragment. Exported as the single source of truth so the drift guard and tests
 * reference the same literal the generator writes — the cl-tofu pipeline wires a
 * processor of this exact name into its `traces/posthog` leg.
 */
export const POSTHOG_FILTER_PROCESSOR_NAME = "filter/product_signals";

export const POSTHOG_IDENTITY_PROCESSOR_NAME = "transform/posthog_identity";

export const PosthogIdentityAttribute = {
  DistinctId: "posthog.distinct_id",
} as const;
export type PosthogIdentityAttribute =
  (typeof PosthogIdentityAttribute)[keyof typeof PosthogIdentityAttribute];

const GENERATOR_REFERENCE =
  "packages/telemetry-contract/scripts/generate-collector-posthog-routing.ts";
const REGENERATE_COMMAND =
  "pnpm --filter @closedloop-ai/telemetry-contract generate:collector-posthog-routing";
const POSTHOG_IDENTITY_SOURCE_KEY = TelemetryAttribute.AppInstallationId;
const POSTHOG_IDENTITY_TARGET_KEY = PosthogIdentityAttribute.DistinctId;

/**
 * The otelcol `filter` processor drops every span whose OTTL condition is true.
 * A span is a product signal when it carries *any* marker key, so the PostHog
 * leg must drop spans where *all* marker keys are absent — expressed as a single
 * conjunction of `attributes["<key>"] == nil` clauses.
 */
function renderDropNonProductSignalCondition(keys: readonly string[]): string {
  if (keys.length === 0) {
    throw new Error(
      "CollectorProductSignalAttributeKeys is empty: a PostHog routing filter with no marker keys would drop every span. Add at least one marker attribute to the contract."
    );
  }
  return keys.map((key) => `attributes["${key}"] == nil`).join(" and ");
}

export function renderCollectorPosthogRoutingManifest(
  keys: readonly string[] = CollectorProductSignalAttributeKeys
): string {
  return `${JSON.stringify(
    {
      $generatedBy: GENERATOR_REFERENCE,
      $doNotEdit: `Generated from CollectorProductSignalAttributeKeys; run \`${REGENERATE_COMMAND}\` to regenerate (FEA-1991).`,
      markerKeys: [...keys],
    },
    null,
    2
  )}\n`;
}

export function renderCollectorPosthogRoutingFragment(
  keys: readonly string[] = CollectorProductSignalAttributeKeys
): string {
  const header = [
    `# GENERATED by ${GENERATOR_REFERENCE} — DO NOT EDIT BY HAND.`,
    "# otelcol `filter` processor fragment for the keyless-telemetry collector's",
    "# PostHog leg. Keeps only product-signal spans (GenAI generations, marked by",
    "# the contract's gen_ai discriminator) so they fan out to PostHog alongside",
    "# the Datadog ops leg; every other span is dropped from the PostHog pipeline.",
    "# `error_mode: ignore` keeps a span on a malformed condition rather than",
    "# dropping it — redaction has already run, so an over-send is harmless.",
    "# Vendor this into the cl-tofu collector config (cross-repo) and regenerate",
    "# from @closedloop-ai/telemetry-contract on any",
    "# CollectorProductSignalAttributeKeys change (FEA-1991):",
    `#   ${REGENERATE_COMMAND}`,
  ].join("\n");
  assertYamlSafeKeys(keys, "the PostHog routing filter fragment");
  const condition = renderDropNonProductSignalCondition(keys);
  return `${header}\n${POSTHOG_FILTER_PROCESSOR_NAME}:\n  error_mode: ignore\n  traces:\n    span:\n      - '${condition}'\n`;
}

export function renderCollectorPosthogIdentityManifest(): string {
  return `${JSON.stringify(
    {
      $generatedBy: GENERATOR_REFERENCE,
      $doNotEdit: `Generated from TelemetryAttribute.AppInstallationId and PosthogIdentityAttribute.DistinctId; run \`${REGENERATE_COMMAND}\` to regenerate (FEA-2184).`,
      processorName: POSTHOG_IDENTITY_PROCESSOR_NAME,
      sourceKey: POSTHOG_IDENTITY_SOURCE_KEY,
      targetKey: POSTHOG_IDENTITY_TARGET_KEY,
    },
    null,
    2
  )}\n`;
}

export function renderCollectorPosthogIdentityFragment(): string {
  const header = [
    `# GENERATED by ${GENERATOR_REFERENCE} — DO NOT EDIT BY HAND.`,
    "# otelcol `transform` processor fragment for the keyless-telemetry collector's",
    "# PostHog leg. Copies the vendor-neutral anonymous installation id into",
    "# PostHog's OTLP person key only after redaction and product-signal filtering.",
    "# Missing installation ids are left unset so older Desktop builds keep the",
    "# current PostHog fallback behavior.",
    "# Vendor this into the cl-tofu collector config (cross-repo) after",
    "# `redaction` and `filter/product_signals` in the `traces/posthog` pipeline",
    "# and regenerate from @closedloop-ai/telemetry-contract on any FEA-2184",
    "# identity mapping change:",
    `#   ${REGENERATE_COMMAND}`,
  ].join("\n");
  assertYamlSafeKeys(
    [POSTHOG_IDENTITY_SOURCE_KEY, POSTHOG_IDENTITY_TARGET_KEY],
    "the PostHog identity transform fragment"
  );
  return `${header}\n${POSTHOG_IDENTITY_PROCESSOR_NAME}:\n  error_mode: ignore\n  trace_statements:\n    - context: resource\n      statements:\n        - 'set(attributes["${POSTHOG_IDENTITY_TARGET_KEY}"], attributes["${POSTHOG_IDENTITY_SOURCE_KEY}"]) where attributes["${POSTHOG_IDENTITY_SOURCE_KEY}"] != nil'\n`;
}

export function collectorPosthogRoutingArtifacts(
  keys: readonly string[] = CollectorProductSignalAttributeKeys
): {
  fragmentYaml: string;
  identityFragmentYaml: string;
  identityManifestJson: string;
  manifestJson: string;
} {
  return {
    fragmentYaml: renderCollectorPosthogRoutingFragment(keys),
    identityFragmentYaml: renderCollectorPosthogIdentityFragment(),
    identityManifestJson: renderCollectorPosthogIdentityManifest(),
    manifestJson: renderCollectorPosthogRoutingManifest(keys),
  };
}

export function writeCollectorPosthogRoutingSources(): void {
  const {
    fragmentYaml,
    identityFragmentYaml,
    identityManifestJson,
    manifestJson,
  } = collectorPosthogRoutingArtifacts();
  writeGeneratedArtifact(CollectorPosthogRoutingPath.Manifest, manifestJson);
  writeGeneratedArtifact(CollectorPosthogRoutingPath.Fragment, fragmentYaml);
  writeGeneratedArtifact(
    CollectorPosthogIdentityPath.Manifest,
    identityManifestJson
  );
  writeGeneratedArtifact(
    CollectorPosthogIdentityPath.Fragment,
    identityFragmentYaml
  );
}

if (process.argv[1]?.endsWith("generate-collector-posthog-routing.ts")) {
  writeCollectorPosthogRoutingSources();
}
