import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import YAML from "yaml";
import {
  assertValidPolicy,
  CollectorTailSamplingPolicy,
  ERROR_STATUS_CODE,
} from "../collector-tail-sampling-policy";

// The typed policy SSOT now lives in `../collector-tail-sampling-policy` so the
// desktop IPC perf head-sampler (FEA-1997) can reuse the same thresholds.
// Importers of the policy now take it from that module directly; this file owns
// only the YAML rendering of the fragment.

/**
 * C4 codegen (FEA-1992): emit the keyless-telemetry collector `tail_sampling`
 * processor fragment from a typed policy SSOT.
 *
 * One committed artifact is produced — a ready-to-vendor otelcol `tail_sampling`
 * processor fragment. The cl-tofu collector config (PRD-481 C2 / FEA-1990)
 * vendors the fragment into its TRACES pipeline instead of hand-maintaining the
 * policy; the drift guard (`check-collector-tail-sampling.ts`) re-runs this
 * rendering in memory and fails the build if the committed copy is stale.
 *
 * Scope: `tail_sampling` is a TRACE processor, so this governs the collector's
 * traces pipeline only (logs/metrics are unaffected). The policy keeps every
 * error and slow/p99-latency trace at 100% and samples the rest at a fixed
 * baseline rate — the cost-control lever for Datadog ingest at fleet scale.
 *
 * The rendering is a pure function of {@link CollectorTailSamplingPolicy}, so the
 * artifact only changes when the policy changes — not on unrelated version bumps.
 */

export const CollectorTailSamplingPath = {
  Fragment: "collector/tail-sampling.yaml",
} as const;

const GENERATOR_REFERENCE =
  "packages/telemetry-contract/scripts/generate-collector-tail-sampling.ts";
/** Owner of the regenerate command; the drift guard composes its hint from this. */
export const REGENERATE_COMMAND =
  "pnpm --filter @closedloop-ai/telemetry-contract generate:collector-tail-sampling";

/**
 * Build the plain otelcol `tail_sampling` config object. Policies are combined
 * by the processor's native OR semantics — a trace is kept if ANY policy votes
 * to keep — so the three keep-policies guarantee 100% retention of errors and
 * slow traces while `baseline` samples the remainder.
 */
function buildTailSamplingConfig(
  policy: CollectorTailSamplingPolicy
): Record<string, unknown> {
  return {
    tail_sampling: {
      decision_wait: `${policy.decisionWaitSeconds}s`,
      num_traces: policy.numTraces,
      expected_new_traces_per_sec: policy.expectedNewTracesPerSec,
      policies: [
        {
          name: policy.policyNames.errorStatus,
          type: "status_code",
          status_code: { status_codes: [ERROR_STATUS_CODE] },
        },
        {
          name: policy.policyNames.serverErrors,
          type: "numeric_attribute",
          numeric_attribute: {
            key: policy.serverErrorAttributeKey,
            min_value: policy.serverErrorStatusRange.min,
            max_value: policy.serverErrorStatusRange.max,
          },
        },
        {
          name: policy.policyNames.slow,
          type: "latency",
          latency: { threshold_ms: policy.slowLatencyThresholdMs },
        },
        {
          name: policy.policyNames.baseline,
          type: "probabilistic",
          probabilistic: {
            sampling_percentage: policy.baselineSamplingPercentage,
          },
        },
      ],
    },
  };
}

export function renderCollectorTailSamplingFragment(
  policy: CollectorTailSamplingPolicy = CollectorTailSamplingPolicy
): string {
  assertValidPolicy(policy);
  const header = [
    `# GENERATED by ${GENERATOR_REFERENCE} — DO NOT EDIT BY HAND.`,
    "# otelcol `tail_sampling` processor fragment for the keyless-telemetry collector.",
    "# Trace-only: vendor this into the cl-tofu collector config TRACES pipeline",
    "# (cross-repo) and regenerate from @closedloop-ai/telemetry-contract on any",
    "# policy change (FEA-1992):",
    `#   ${REGENERATE_COMMAND}`,
    "# Keeps every error (span status ERROR or HTTP 5xx) and slow/p99-latency",
    "# trace at 100%; samples the rest at the baseline rate (OR semantics).",
  ].join("\n");
  const body = YAML.stringify(buildTailSamplingConfig(policy), { indent: 2 });
  return `${header}\n${body}`;
}

export function collectorTailSamplingArtifacts(
  policy: CollectorTailSamplingPolicy = CollectorTailSamplingPolicy
): { fragmentYaml: string } {
  return { fragmentYaml: renderCollectorTailSamplingFragment(policy) };
}

export function writeCollectorTailSamplingSources(): void {
  const { fragmentYaml } = collectorTailSamplingArtifacts();
  mkdirSync(dirname(CollectorTailSamplingPath.Fragment), { recursive: true });
  writeFileSync(CollectorTailSamplingPath.Fragment, fragmentYaml);
}

if (process.argv[1]?.endsWith("generate-collector-tail-sampling.ts")) {
  writeCollectorTailSamplingSources();
}
