import { CollectorAllowedAttributeKeys } from "../src/attributes";
import {
  assertYamlSafeKeys,
  writeGeneratedArtifact,
} from "./collector-codegen-common";

/**
 * O2 codegen (FEA-2170): emit the keyless-telemetry collector allow-list from
 * the contract's `TelemetryAttribute` SSOT (via {@link CollectorAllowedAttributeKeys}).
 *
 * Two committed artifacts are produced — a machine-readable JSON manifest and a
 * ready-to-vendor otelcol `redaction` processor fragment. The cl-tofu collector
 * config vendors the fragment instead of hand-maintaining `allowed_keys`
 * (cross-repo follow-up); the drift guard (`check-collector-allowlist.ts`)
 * re-runs this rendering in memory and fails the build if the committed copies
 * are stale or diverge from the contract. The rendering is a pure function of
 * the key set, so the artifacts only change when attributes change — not on
 * unrelated package version bumps.
 */

export const CollectorAllowlistPath = {
  Manifest: "collector/allowed-attributes.json",
  Fragment: "collector/keyless-telemetry-redaction.yaml",
} as const;

const GENERATOR_REFERENCE =
  "packages/telemetry-contract/scripts/generate-collector-allowlist.ts";
const REGENERATE_COMMAND =
  "pnpm --filter @closedloop-ai/telemetry-contract generate:collector-allowlist";

export function renderCollectorAllowlistManifest(
  keys: readonly string[] = CollectorAllowedAttributeKeys
): string {
  return `${JSON.stringify(
    {
      $generatedBy: GENERATOR_REFERENCE,
      $doNotEdit: `Generated from TelemetryAttribute; run \`${REGENERATE_COMMAND}\` to regenerate (FEA-2170).`,
      allowAllKeys: false,
      allowedKeys: [...keys],
    },
    null,
    2
  )}\n`;
}

export function renderCollectorRedactionFragment(
  keys: readonly string[] = CollectorAllowedAttributeKeys
): string {
  const header = [
    `# GENERATED by ${GENERATOR_REFERENCE} — DO NOT EDIT BY HAND.`,
    "# otelcol `redaction` processor fragment for the keyless-telemetry collector.",
    "# Vendor this into the cl-tofu collector config (cross-repo) and regenerate",
    "# from @closedloop-ai/telemetry-contract on any TelemetryAttribute change",
    "# (FEA-2170):",
    `#   ${REGENERATE_COMMAND}`,
  ].join("\n");
  assertYamlSafeKeys(keys, "the redaction allow-list fragment");
  const allowedKeys = keys.map((key) => `    - ${key}`).join("\n");
  return `${header}\nredaction:\n  allow_all_keys: false\n  allowed_keys:\n${allowedKeys}\n`;
}

export function collectorAllowlistArtifacts(
  keys: readonly string[] = CollectorAllowedAttributeKeys
): { manifestJson: string; fragmentYaml: string } {
  return {
    manifestJson: renderCollectorAllowlistManifest(keys),
    fragmentYaml: renderCollectorRedactionFragment(keys),
  };
}

export function writeCollectorAllowlistSources(): void {
  const { manifestJson, fragmentYaml } = collectorAllowlistArtifacts();
  writeGeneratedArtifact(CollectorAllowlistPath.Manifest, manifestJson);
  writeGeneratedArtifact(CollectorAllowlistPath.Fragment, fragmentYaml);
}

if (process.argv[1]?.endsWith("generate-collector-allowlist.ts")) {
  writeCollectorAllowlistSources();
}
