import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  DockerInfraError,
  dockerAvailable,
  runVerification,
  type VerificationReport,
} from "../collector-verification/run-verification";

/**
 * CLI for the collector tail-sampling mechanical verification (FEA-2182).
 *
 * Boots a real otelcol-contrib collector with the committed `tail_sampling`
 * fragment, drives synthetic OTLP traffic through each policy leg, and reports
 * the result against the collector's own decision metrics + the file-exporter
 * ground truth.
 *
 *   pnpm --filter @closedloop-ai/telemetry-contract verify:collector-tail-sampling
 *   pnpm --filter @closedloop-ai/telemetry-contract verify:collector-tail-sampling --write
 *
 * `--write` regenerates the committed `collector-verification/VERIFICATION.md`
 * evidence artifact. Exits 0 on pass (or when Docker is unavailable — the run is
 * skipped, not failed), 1 on a failing leg.
 */

const ARTIFACT_PATH = new URL(
  "../collector-verification/VERIFICATION.md",
  import.meta.url
);

function renderReportLines(report: VerificationReport): string[] {
  const lines = [
    `Collector image: ${report.image}`,
    `Synthetic traces sent: ${report.totalSent} (errors=${report.counts.errors}, server-errors=${report.counts.serverErrors}, slow=${report.counts.slow}, baseline=${report.counts.baseline})`,
    "",
    "Per-leg results:",
  ];
  for (const leg of report.evaluation.legs) {
    lines.push(
      `  ${leg.pass ? "PASS" : "FAIL"}  ${leg.scenario}: ${leg.detail}`
    );
  }
  lines.push("");
  lines.push(`Overall: ${report.evaluation.pass ? "PASS" : "FAIL"}`);
  return lines;
}

function renderArtifact(report: VerificationReport, isoDate: string): string {
  const legRows = report.evaluation.legs
    .map(
      (leg) =>
        `| \`${leg.scenario}\` | \`${leg.policyName}\` | ${leg.sent} | ${leg.retainedInFile} | ${leg.decisionSampledTrue} | ${leg.pass ? "✅" : "❌"} |`
    )
    .join("\n");

  const metricRows = [...report.rawMetrics.entries()]
    .map(
      ([policy, decision]) =>
        `| \`${policy}\` | ${decision.sampledTrue} | ${decision.sampledFalse} |`
    )
    .join("\n");

  return `# Tail-sampling mechanical verification (FEA-2182)

> Generated by \`pnpm --filter @closedloop-ai/telemetry-contract verify:collector-tail-sampling --write\`.
> Regenerate after any change to the policy SSOT or the committed fragment.

**Run date:** ${isoDate}
**Collector:** \`${report.image}\`
**Outcome:** ${report.evaluation.pass ? "✅ PASS" : "❌ FAIL"}

A real otelcol-contrib collector was booted with the committed
\`collector/tail-sampling.yaml\` fragment (verbatim) on a minimal
\`otlp → tail_sampling → file\` traces pipeline. Synthetic OTLP traces were
pushed to exercise each policy leg, and the outcome was checked against **both**
the collector's own decision metrics
(\`otelcol_processor_tail_sampling_count_traces_sampled\`) and the file
exporter's ground truth.

## Per-leg results

| Scenario | Keep policy | Sent | Retained (file) | Decision \`sampled=true\` | Result |
| --- | --- | ---: | ---: | ---: | :---: |
${legRows}

Errors, HTTP 5xx, and slow (> threshold) traces are retained at 100%; baseline
(normal) traces are sampled to a strict subset by the probabilistic policy.

## Raw decision metrics

\`otelcol_processor_tail_sampling_count_traces_sampled\`, by policy:

| Policy | \`sampled=true\` | \`sampled=false\` |
| --- | ---: | ---: |
${metricRows}

## Reproduce

\`\`\`bash
pnpm --filter @closedloop-ai/telemetry-contract verify:collector-tail-sampling
# add --write to regenerate this file
\`\`\`

Requires a reachable Docker daemon. This is an on-demand verification, not a
gate test — re-run it (and regenerate this file) after any change to the policy
SSOT, the committed fragment, or the pinned otelcol image.
`;
}

async function main(): Promise<number> {
  const write = process.argv.includes("--write");

  if (!(await dockerAvailable())) {
    console.error(
      "Docker is not reachable — skipping tail-sampling verification (nothing to do)."
    );
    return 0;
  }

  let report: VerificationReport;
  try {
    report = await runVerification({
      log: (message) => console.error(`[verify] ${message}`),
    });
  } catch (error) {
    if (error instanceof DockerInfraError) {
      console.error(`${error.message} — skipping (nothing to do).`);
      return 0;
    }
    throw error;
  }

  for (const line of renderReportLines(report)) {
    console.log(line);
  }

  if (write) {
    // Stamp the date outside the pure renderer (kept clock-free for testing).
    const isoDate = new Date().toISOString().slice(0, 10);
    writeFileSync(
      fileURLToPath(ARTIFACT_PATH),
      renderArtifact(report, isoDate)
    );
    console.log(`\nWrote ${fileURLToPath(ARTIFACT_PATH)}`);
  }

  return report.evaluation.pass ? 0 : 1;
}

if (process.argv[1]?.endsWith("verify-collector-tail-sampling.ts")) {
  main()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    });
}

export { renderArtifact, renderReportLines };
