import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "index.tsx",
    "lib/fonts.ts",
    "components/ui/active-filters-bar.tsx",
    "components/ui/alert-dialog.tsx",
    "components/ui/alert.tsx",
    "components/ui/analytics-range-toggle.tsx",
    "components/ui/avatar.tsx",
    "components/ui/badge.tsx",
    "components/ui/breadcrumb.tsx",
    "components/ui/button.tsx",
    "components/ui/calendar.tsx",
    "components/ui/card.tsx",
    "components/ui/category-bar-chart.tsx",
    "components/ui/chart.tsx",
    "components/ui/chart-colors.ts",
    "components/ui/checkbox.tsx",
    "components/ui/donut-chart.tsx",
    "components/ui/time-series-area-chart.tsx",
    "components/ui/chip.tsx",
    "components/ui/collapsible.tsx",
    "components/ui/collapsible-section.tsx",
    "components/ui/collapsed-comment-row.tsx",
    "components/ui/comment-action-menu.tsx",
    "components/ui/comment-composer.tsx",
    "components/ui/comment-thread.tsx",
    "components/ui/comment-thread-action-footer.tsx",
    "components/ui/command.tsx",
    "components/ui/conversation-message.tsx",
    "components/ui/conversation-transcript.tsx",
    "components/ui/data-table.tsx",
    "components/ui/date-picker-popover.tsx",
    "components/ui/dialog.tsx",
    "components/ui/drawer.tsx",
    "components/ui/dropdown-menu.tsx",
    "components/ui/empty-state.tsx",
    "components/ui/favorite-button.tsx",
    "components/ui/feed-rail.tsx",
    "components/ui/filter-popover.tsx",
    "components/ui/filter-chip.tsx",
    "components/ui/form.tsx",
    "components/ui/group-section-header.tsx",
    "components/ui/inline-edit-editor-shell.tsx",
    "components/ui/input.tsx",
    "components/ui/label.tsx",
    "components/ui/metadata-panel.tsx",
    "components/ui/mode-toggle.tsx",
    "components/ui/pagination.tsx",
    "components/ui/table-pagination.tsx",
    "components/ui/popover.tsx",
    "components/ui/priority-badge.tsx",
    "components/ui/priority-icon.tsx",
    "components/ui/progress.tsx",
    "components/ui/radio-group.tsx",
    "components/ui/resizable.tsx",
    "components/ui/scroll-area.tsx",
    "components/ui/section-header.tsx",
    "components/ui/select.tsx",
    "components/ui/separator.tsx",
    "components/ui/sheet.tsx",
    "components/ui/sidebar.tsx",
    "components/ui/sidebar-collapsible-section.tsx",
    "components/ui/sidebar-count-badge.tsx",
    "components/ui/skeleton.tsx",
    "components/ui/sonner.tsx",
    "components/ui/sortable-column-header.tsx",
    "components/ui/status-icon.tsx",
    "components/ui/status-metadata-section.tsx",
    "components/ui/status-percentage-icon.tsx",
    "components/ui/star-rating.tsx",
    "components/ui/switch.tsx",
    "components/ui/table.tsx",
    "components/ui/table-grid-header.tsx",
    "components/ui/grid-table.tsx",
    "components/ui/table-filter-menu.tsx",
    "components/ui/table-placeholder-actions.tsx",
    "components/ui/table-view-menu.tsx",
    "components/ui/table-filters.ts",
    "components/ui/tabs.tsx",
    "components/ui/textarea.tsx",
    "components/ui/theme-submenu.tsx",
    "components/ui/toggle-group.tsx",
    "components/ui/toggle.tsx",
    "components/ui/tooltip.tsx",
    "components/ui/user-select-popover.tsx",
    "components/ui/types.ts",
    "components/ui/utils.ts",
    "components/ui/primitives/*.tsx",
    "components/ui/layout/*.tsx",
    "storybook/component-catalog.ts",
    "storybook/mock-data.ts",
    "hooks/use-copy-to-clipboard.ts",
    "hooks/use-media-query.ts",
    "hooks/use-mobile.ts",
    "providers/theme.tsx",
    "lib/utils.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  sourcemap: true,
  outExtension({ format }) {
    return {
      js: format === "esm" ? ".js" : ".cjs",
    };
  },
  esbuildOptions(options) {
    options.jsx = "automatic";
  },
});
