// GENERATED by scripts/generate-audit-character-roster.mjs — DO NOT EDIT.
// Regenerated by `pnpm prebuild`; drift-guarded by `pnpm verify:audit-roster`.
// Source of truth: apps/desktop/resources/audit-characters/**/*.md (FEA-4013).

/**
 * One review character in the Audit Bot cast. `id` is the prompt file's path
 * relative to `resources/audit-characters/` (no `.md`) — exactly what the crewd
 * runner resolves — so every entry maps to a prompt the runner can launch.
 */
export type AuditCharacterRosterEntry = {
  /** Prompt-file id relative to the characters dir (e.g. "kaitic/desktop-denny"). */
  id: string;
  /** Display name shown in the picker. */
  label: string;
  /** One-line description of what the character reviews. */
  description: string;
  /** The ClosedLoop tag stamped on every issue this character files. */
  tag: string;
  /** Picker group key: the author folder, or "core" for a top-level character. */
  group: string;
  /** Human heading for {@link AuditCharacterRosterEntry.group} (e.g. "Kai Tic"). */
  groupLabel: string;
};

/**
 * The full cast of Audit Bot review characters, discovered from the shipped
 * prompt files. Sorted by id; grouped for display by {@link AuditCharacterRosterEntry.group}.
 */
export const AUDIT_CHARACTER_ROSTER: readonly AuditCharacterRosterEntry[] = [
  {
    id: "chrisc/architect-art",
    label: "Architect Art",
    description: "The architecture & contracts guardian.",
    tag: "agent-chrisc-architect-art",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "chrisc/contract-cora",
    label: "Contract Cora",
    description: "The API-contract synchronization specialist.",
    tag: "agent-chrisc-contract-cora",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "chrisc/metrics-mira",
    label: "Metrics Mira",
    description: "The data-parsing, metrics-correctness & insights expert.",
    tag: "agent-chrisc-metrics-mira",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "chrisc/perf-pete",
    label: "Perf Pete",
    description: "The performance watchdog.",
    tag: "agent-chrisc-perf-pete",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "chrisc/query-quinn",
    label: "Quinn the Query Optimizer",
    description: "The big-data, aggregation & query-scaling expert.",
    tag: "agent-chrisc-query-quinn",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "chrisc/resilience-rita",
    label: "Resilience Rita",
    description: "The idempotency & failure-mode specialist.",
    tag: "agent-chrisc-resilience-rita",
    group: "chrisc",
    groupLabel: "Chris C",
  },
  {
    id: "code-cassandra",
    label: "Code Cassandra",
    description: "Correctness & bug audit.",
    tag: "agent-code-cassandra",
    group: "core",
    groupLabel: "Core",
  },
  {
    id: "danielochoa/agent-aiden",
    label: "Agent Aiden",
    description: "The LLM/agent-loop engineering expert.",
    tag: "agent-danielochoa-agent-aiden",
    group: "danielochoa",
    groupLabel: "Daniel Ochoa",
  },
  {
    id: "danielochoa/dx-drew",
    label: "DX Drew",
    description: "The developer-experience & public API/SDK ergonomics expert.",
    tag: "agent-danielochoa-dx-drew",
    group: "danielochoa",
    groupLabel: "Daniel Ochoa",
  },
  {
    id: "danielochoa/mcp-morgan",
    label: "MCP Morgan",
    description: "The Model Context Protocol server expert.",
    tag: "agent-danielochoa-mcp-morgan",
    group: "danielochoa",
    groupLabel: "Daniel Ochoa",
  },
  {
    id: "danielochoa/stream-stella",
    label: "Stream Stella",
    description: "The real-time & streaming expert.",
    tag: "agent-danielochoa-stream-stella",
    group: "danielochoa",
    groupLabel: "Daniel Ochoa",
  },
  {
    id: "docs-darwin",
    label: "Docs Darwin",
    description: "Documentation-vs-code audit.",
    tag: "agent-docs-darwin",
    group: "core",
    groupLabel: "Core",
  },
  {
    id: "kaitic/a11y-alex",
    label: "A11y Alex",
    description: "The accessibility checker.",
    tag: "agent-kaitic-a11y-alex",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/barry-the-bug-basher",
    label: "Barry the Bug Basher",
    description: "Recent-PR bug hunt, fix, and sprint pickup.",
    tag: "agent-kaitic-barry-the-bug-basher",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/designer-dana",
    label: "Designer Dana",
    description: "The design-system and shared app UI ownership scout.",
    tag: "agent-kaitic-designer-dana",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/desktop-denny",
    label: "Desktop Denny",
    description: "The exploratory QA marauder for the apps/desktop Electron app.",
    tag: "agent-kaitic-desktop-denny",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/docs-darwin",
    label: "Docs Darwin (Kai Tic)",
    description: "The documentation maintainer.",
    tag: "agent-kaitic-docs-darwin",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/flags-fiona",
    label: "Flags Fiona",
    description: "The feature-flag lifecycle & hygiene expert.",
    tag: "agent-kaitic-flags-fiona",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/storyteller-steve",
    label: "Storyteller Steve",
    description: "The Storybook coverage guardian.",
    tag: "agent-kaitic-storyteller-steve",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/ux-ursula",
    label: "UX Ursula",
    description: "The event handler & UX bug hunter.",
    tag: "agent-kaitic-ux-ursula",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/vex-the-vqa-marauder",
    label: "Vex the VQA Marauder",
    description: "The visual QA guardian.",
    tag: "agent-kaitic-vex-the-vqa-marauder",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "kaitic/vinnie-the-validator",
    label: "Vinnie the Validator",
    description: "The requirements-driven Electron Visual QA reviewer for the apps/desktop Electron app.",
    tag: "agent-kaitic-vinnie-the-validator",
    group: "kaitic",
    groupLabel: "Kai Tic",
  },
  {
    id: "mikeangstadt/cost-cody",
    label: "Cost Cody",
    description: "The LLM token-accounting correctness & cost-efficiency expert.",
    tag: "agent-mikeangstadt-cost-cody",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/cutter-carl",
    label: "Cutter Carl",
    description: "The dead-code exterminator.",
    tag: "agent-mikeangstadt-cutter-carl",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/dba-dexter",
    label: "Dexter the DBA",
    description: "The database schema, migration & transaction-correctness expert.",
    tag: "agent-mikeangstadt-dba-dexter",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/denise-the-deduper",
    label: "Denise the Deduper",
    description: "The duplicate code hunter.",
    tag: "agent-mikeangstadt-denise-the-deduper",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/electron-eli",
    label: "Electron Eli",
    description: "The Electron main-process & IPC security/hardening expert.",
    tag: "agent-mikeangstadt-electron-eli",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/ingest-iris",
    label: "Ingest-Iris",
    description: "The auditor of transcript / session-log ingestion.",
    tag: "agent-mikeangstadt-ingest-iris",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/react-rachel",
    label: "React Rachel",
    description: "The React correctness & idiom expert.",
    tag: "agent-mikeangstadt-react-rachel",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/richtext-rina",
    label: "Richtext Rina",
    description: "The rich-text editor (Tiptap/ProseMirror) & content-rendering expert.",
    tag: "agent-mikeangstadt-richtext-rina",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/schema-stew",
    label: "Schema Stew",
    description: "The desktop↔cloud sync-schema alignment expert.",
    tag: "agent-mikeangstadt-schema-stew",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "mikeangstadt/storage-stefan",
    label: "Storage Stefan",
    description: "The storage efficiency, cost & interaction-UX expert.",
    tag: "agent-mikeangstadt-storage-stefan",
    group: "mikeangstadt",
    groupLabel: "Mike Angstadt",
  },
  {
    id: "perf-pathfinder",
    label: "Perf Pathfinder",
    description: "Performance audit.",
    tag: "agent-perf-pathfinder",
    group: "core",
    groupLabel: "Core",
  },
  {
    id: "peteru/correctness-cari",
    label: "Correctness Cari",
    description: "The type safety & correctness gate.",
    tag: "agent-peteru-correctness-cari",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "peteru/pipeline-pat",
    label: "Pipeline Pat",
    description: "The CI/CD & GitHub Actions specialist.",
    tag: "agent-peteru-pipeline-pat",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "peteru/privacy-piper",
    label: "Privacy Piper",
    description: "The PII & data-governance expert.",
    tag: "agent-peteru-privacy-piper",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "peteru/steve-the-sec-engineer",
    label: "Steve the Sec Engineer",
    description: "The security auditor.",
    tag: "agent-peteru-steve-the-sec-engineer",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "peteru/testing-tina",
    label: "Testing Tina",
    description: "The test coverage guardian.",
    tag: "agent-peteru-testing-tina",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "peteru/trace-tracy",
    label: "Trace Tracy",
    description: "The observability.",
    tag: "agent-peteru-trace-tracy",
    group: "peteru",
    groupLabel: "Pete U",
  },
  {
    id: "security-sentinel",
    label: "Security Sentinel",
    description: "Vulnerability audit.",
    tag: "agent-security-sentinel",
    group: "core",
    groupLabel: "Core",
  },
  {
    id: "thadeusb/golden-gary",
    label: "Golden Gary",
    description: "The craftsman-steward of the golden dataset.",
    tag: "agent-thadeusb-golden-gary",
    group: "thadeusb",
    groupLabel: "Thadeus B",
  },
];
