/** Sample Branches rows for stories and local fixtures only. */

import { type BranchRow, BranchRowStatus } from "./branch-row";

export const BRANCH_SAMPLE_ROWS: BranchRow[] = [
  {
    id: "br_1270",
    branchName: "agent/repo-overrides-workspace-config",
    baseBranch: "main",
    repo: "closedloop-web",
    owner: "Parker Byrd",
    status: BranchRowStatus.Merged,
    prNumber: 1270,
    prTitle: "Migrate repositoryOverrides → workspace config",
    prUrl: "https://github.com/closedloop-ai/closedloop-web/pull/1270",
    prState: "MERGED",
    checksPassed: 12,
    checksTotal: 12,
    checksStatus: "PASSING",
    behind: 0,
    ahead: 2,
    additions: 261,
    deletions: 150,
    sessionCount: 3,
    commentCount: null,
    lastActivityLabel: "2h ago",
  },
  {
    id: "br_1271",
    branchName: "agent/repo-overrides-backfill",
    baseBranch: "main",
    repo: "closedloop-web",
    owner: "Parker Byrd",
    status: BranchRowStatus.Merged,
    prNumber: 1271,
    prTitle: "Backfill workspace_settings + keep legacy alias",
    prUrl: "https://github.com/closedloop-ai/closedloop-web/pull/1271",
    prState: "MERGED",
    checksPassed: 12,
    checksTotal: 12,
    checksStatus: "PASSING",
    behind: 0,
    ahead: 2,
    additions: 268,
    deletions: 0,
    sessionCount: 2,
    commentCount: null,
    lastActivityLabel: "2h ago",
  },
  {
    id: "br_1284",
    branchName: "agent/synthetic-seed-generator",
    baseBranch: "main",
    repo: "symphony-alpha",
    owner: "Alex Rivera",
    status: BranchRowStatus.Review,
    prNumber: 1284,
    prTitle: "Synthetic seed generator for fixtures",
    prUrl: "https://github.com/closedloop-ai/symphony-alpha/pull/1284",
    prState: "OPEN",
    checksPassed: 9,
    checksTotal: 11,
    checksStatus: "FAILING",
    behind: 3,
    ahead: 4,
    additions: 412,
    deletions: 38,
    sessionCount: 4,
    commentCount: null,
    lastActivityLabel: "1h ago",
  },
  {
    id: "br_1281",
    branchName: "agent/inbox-realtime-v2",
    baseBranch: "main",
    repo: "closedloop-web",
    owner: "Sam Chen",
    status: BranchRowStatus.Open,
    prNumber: 1281,
    prTitle: "Inbox v2 — realtime updates",
    prUrl: "https://github.com/closedloop-ai/closedloop-web/pull/1281",
    prState: "OPEN",
    checksPassed: 12,
    checksTotal: 12,
    checksStatus: "PASSING",
    behind: 1,
    ahead: 6,
    additions: 188,
    deletions: 44,
    sessionCount: 2,
    commentCount: null,
    lastActivityLabel: "3h ago",
  },
  {
    id: "br_session_cost",
    branchName: "fix/session-cost-rounding",
    baseBranch: "develop",
    repo: "closedloop-api",
    owner: "Jordan Lee",
    status: BranchRowStatus.Draft,
    prNumber: null,
    prTitle: null,
    prUrl: null,
    prState: null,
    checksPassed: null,
    checksTotal: null,
    checksStatus: null,
    behind: 0,
    ahead: 1,
    additions: 24,
    deletions: 6,
    sessionCount: 1,
    commentCount: null,
    lastActivityLabel: "5h ago",
  },
  {
    id: "br_1289",
    branchName: "agent/skill-registry-loader",
    baseBranch: "main",
    repo: "infra",
    owner: "Alex Rivera",
    status: BranchRowStatus.Blocked,
    prNumber: 1289,
    prTitle: "Skill registry loader",
    prUrl: "https://github.com/closedloop-ai/infra/pull/1289",
    prState: "OPEN",
    checksPassed: 3,
    checksTotal: 9,
    checksStatus: "FAILING",
    behind: 8,
    ahead: 3,
    additions: 96,
    deletions: 210,
    sessionCount: 5,
    commentCount: null,
    lastActivityLabel: "1d ago",
  },
  {
    id: "br_saml",
    branchName: "agent/saml-sso-implementation",
    baseBranch: "main",
    repo: "symphony-alpha",
    owner: "Sam Chen",
    status: BranchRowStatus.Open,
    prNumber: 1290,
    prTitle: "SAML SSO — implementation",
    prUrl: "https://github.com/closedloop-ai/symphony-alpha/pull/1290",
    prState: "OPEN",
    checksPassed: 10,
    checksTotal: 12,
    checksStatus: "FAILING",
    behind: 2,
    ahead: 5,
    additions: 540,
    deletions: 72,
    sessionCount: 3,
    commentCount: null,
    lastActivityLabel: "6h ago",
  },
  {
    id: "br_dark_mode",
    branchName: "agent/design-system-dark-mode",
    baseBranch: "main",
    repo: "closedloop-web",
    owner: "Jordan Lee",
    status: BranchRowStatus.Review,
    prNumber: 1288,
    prTitle: "Implement dark mode",
    prUrl: "https://github.com/closedloop-ai/closedloop-web/pull/1288",
    prState: "OPEN",
    checksPassed: 12,
    checksTotal: 12,
    checksStatus: "PASSING",
    behind: 0,
    ahead: 3,
    additions: 314,
    deletions: 58,
    sessionCount: 2,
    commentCount: null,
    lastActivityLabel: "yesterday",
  },
];
