import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/attachment.ts",
    "src/artifacts.ts",
    "src/branch-view.ts",
    "src/bootstrap-result.ts",
    "src/bundles.ts",
    "src/commands.ts",
    "src/common.ts",
    "src/compute-target.ts",
    "src/context-pack.ts",
    "src/desktop-request.ts",
    "src/document.ts",
    "src/env-vars.ts",
    "src/error-codes.ts",
    "src/events.ts",
    "src/execution-result.ts",
    "src/friendly-error.ts",
    "src/github.ts",
    "src/insights.ts",
    "src/multi-repo-policy.ts",
    "src/observability.ts",
    "src/tokens.ts",
    "src/token-refresh.ts",
    "src/genai-cost.ts",
    "src/session-status.ts",
    "src/stable-stringify.ts",
    "src/stream-types.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  sourcemap: true,
});
