import type pg from "pg";
import { describe, expect, it, vi } from "vitest";
import {
  cloneDataFromPublic,
  DEFAULT_CLONE_CONNECT_TIMEOUT_MS,
  DEFAULT_CLONE_LOCK_TIMEOUT_MS,
  DEFAULT_CLONE_STATEMENT_TIMEOUT_MS,
  isCloneableColumn,
} from "../clone-schema";

const PREVIEW_SCHEMA = "preview_feature_branch_abc123";
const DATABASE_URL =
  "postgresql://user:pass@db.example.com:5432/closedloop?sslmode=require";

const TABLES_CATALOG_QUERY = /c\.relkind = 'r'/;
const PER_TABLE_TIMING_LOG = /document: 3 rows \(\d+ms\)/;
const CLONE_SUMMARY_TIMING_LOG = /Cloned 1 tables .*\(\d+ms\)/;

type ColumnRow = {
  column_name: string;
  is_enum: boolean;
  is_enum_array: boolean;
  enum_type: string;
  generated: string;
  identity: string;
};

function col(
  overrides: Partial<ColumnRow> & { column_name: string }
): ColumnRow {
  return {
    is_enum: false,
    is_enum_array: false,
    enum_type: "text",
    generated: "",
    identity: "",
    ...overrides,
  };
}

/**
 * A fake pg.Client that records every issued statement and answers the three
 * catalog shapes `cloneDataFromPublic` asks for. `tableColumns` is the target
 * schema's columns; `sourceColumnNames` defaults to every target column name so
 * a test only has to say when the two differ.
 */
function makeClient(opts: {
  tables?: string[];
  tableColumns?: Record<string, ColumnRow[]>;
  sourceColumnNames?: Record<string, string[]>;
  fkEdges?: { child: string; parent: string }[];
  targetFkConstraints?: { table_name: string; constraint_name: string }[];
  requireDeferredBeforeInsert?: boolean;
  failOnConnect?: Error;
  failOnStatement?: { match: RegExp; error: Error };
}) {
  const tables = opts.tables ?? [];
  const issued: string[] = [];
  let constraintsDeferred = false;
  const client = {
    connect: vi.fn(() => {
      if (opts.failOnConnect) {
        return Promise.reject(opts.failOnConnect);
      }
      return Promise.resolve();
    }),
    end: vi.fn(() => Promise.resolve()),
    query: vi.fn((sql: string, params?: unknown[]) => {
      issued.push(sql);
      if (sql === "BEGIN" || sql === "COMMIT" || sql === "ROLLBACK") {
        constraintsDeferred = false;
        return Promise.resolve({ rowCount: null, rows: [] });
      }
      if (sql.startsWith("SET CONSTRAINTS ALL ")) {
        constraintsDeferred = sql === "SET CONSTRAINTS ALL DEFERRED";
        return Promise.resolve({ rowCount: null, rows: [] });
      }
      if (
        sql.startsWith("INSERT INTO") &&
        opts.requireDeferredBeforeInsert &&
        !constraintsDeferred
      ) {
        return Promise.reject(new Error("FK constraints were not deferred"));
      }
      if (opts.failOnStatement?.match.test(sql)) {
        return Promise.reject(opts.failOnStatement.error);
      }
      if (sql.includes("pg_catalog.pg_attribute a")) {
        const schema = String(params?.[0]);
        const table = String(params?.[1]);
        const all = opts.tableColumns?.[table] ?? [];
        if (schema === "public") {
          const names =
            opts.sourceColumnNames?.[table] ?? all.map((c) => c.column_name);
          return Promise.resolve({
            rows: all.filter((c) => names.includes(c.column_name)),
          });
        }
        return Promise.resolve({ rows: all });
      }
      if (sql.includes("c.relkind = 'r'")) {
        return Promise.resolve({
          rows: tables.map((table_name) => ({ table_name })),
        });
      }
      if (sql.includes("con.conname AS constraint_name")) {
        return Promise.resolve({ rows: opts.targetFkConstraints ?? [] });
      }
      if (sql.includes("con.contype = 'f'")) {
        return Promise.resolve({ rows: opts.fkEdges ?? [] });
      }
      // INSERT ... SELECT
      return Promise.resolve({ rowCount: 3 });
    }),
  };
  return { client: client as unknown as pg.Client, issued, spies: client };
}

function makeLogger() {
  return { log: vi.fn(), warn: vi.fn(), error: vi.fn() };
}

describe("isCloneableColumn", () => {
  it("excludes GENERATED ALWAYS and identity columns, keeps ordinary ones", () => {
    expect(isCloneableColumn({ generated: "", identity: "" })).toBe(true);
    // search_documents.tsv (FEA-3857) — the column that broke every clone.
    expect(isCloneableColumn({ generated: "s", identity: "" })).toBe(false);
    // GENERATED ALWAYS AS IDENTITY — Postgres rejects an explicit value.
    expect(isCloneableColumn({ generated: "", identity: "a" })).toBe(false);
    // GENERATED BY DEFAULT AS IDENTITY — Postgres ACCEPTS an explicit value, so
    // it must still be cloned; dropping it would re-number rows and orphan
    // every FK pointing at the original id.
    expect(isCloneableColumn({ generated: "", identity: "d" })).toBe(true);
  });
});

describe("cloneDataFromPublic — statement bounds (ISS-5285)", () => {
  it("sets lock_timeout and statement_timeout BEFORE the first catalog query", async () => {
    const { client, issued } = makeClient({ tables: [] });

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger: makeLogger(),
      env: {},
    });

    const lockIndex = issued.findIndex((sql) => sql.includes("lock_timeout"));
    const statementIndex = issued.findIndex((sql) =>
      sql.includes("statement_timeout")
    );
    const firstCatalogIndex = issued.findIndex((sql) =>
      sql.includes("c.relkind = 'r'")
    );

    expect(lockIndex).toBeGreaterThanOrEqual(0);
    expect(statementIndex).toBeGreaterThanOrEqual(0);
    expect(firstCatalogIndex).toBeGreaterThan(lockIndex);
    expect(firstCatalogIndex).toBeGreaterThan(statementIndex);
    expect(issued[lockIndex]).toContain(`${DEFAULT_CLONE_LOCK_TIMEOUT_MS}ms`);
    expect(issued[statementIndex]).toContain(
      `${DEFAULT_CLONE_STATEMENT_TIMEOUT_MS}ms`
    );
  });

  it("honors env overrides and falls back to defaults on an invalid value", async () => {
    const overridden = makeClient({ tables: [] });
    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => overridden.client,
      logger: makeLogger(),
      env: {
        CLONE_LOCK_TIMEOUT_MS: "1234",
        CLONE_STATEMENT_TIMEOUT_MS: "5678",
      },
    });
    expect(overridden.issued.some((s) => s.includes("1234ms"))).toBe(true);
    expect(overridden.issued.some((s) => s.includes("5678ms"))).toBe(true);

    const invalid = makeClient({ tables: [] });
    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => invalid.client,
      logger: makeLogger(),
      env: {
        CLONE_LOCK_TIMEOUT_MS: "not-a-number",
        CLONE_STATEMENT_TIMEOUT_MS: "-5",
      },
    });
    expect(
      invalid.issued.some((s) =>
        s.includes(`${DEFAULT_CLONE_LOCK_TIMEOUT_MS}ms`)
      )
    ).toBe(true);
    expect(
      invalid.issued.some((s) =>
        s.includes(`${DEFAULT_CLONE_STATEMENT_TIMEOUT_MS}ms`)
      )
    ).toBe(true);
  });

  it("swallows a statement timeout, returns false, and still ends the client", async () => {
    const { client, spies } = makeClient({
      tables: ["document"],
      failOnStatement: {
        match: TABLES_CATALOG_QUERY,
        error: new Error("canceling statement due to statement timeout"),
      },
    });
    const logger = makeLogger();

    const result = await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger,
      env: {},
    });

    expect(result).toBe(false);
    expect(spies.end).toHaveBeenCalledTimes(1);
    expect(logger.error).toHaveBeenCalledWith(
      expect.stringContaining("statement timeout")
    );
  });

  it("bounds the connect itself (pg defaults connectionTimeoutMillis to wait-forever)", async () => {
    const { client } = makeClient({ tables: [] });
    let seen: { connectionTimeoutMillis?: number } | undefined;

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: (_url, opts) => {
        seen = opts;
        return client;
      },
      logger: makeLogger(),
      env: {},
    });

    expect(seen?.connectionTimeoutMillis).toBe(
      DEFAULT_CLONE_CONNECT_TIMEOUT_MS
    );
  });

  it("swallows a CONNECT failure and still ends the client (regression: connect was outside the try)", async () => {
    const { client, spies } = makeClient({
      failOnConnect: new Error(
        'PAM authentication failed for user "vercel_iam"'
      ),
    });
    const logger = makeLogger();

    const result = await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger,
      env: {},
    });

    expect(result).toBe(false);
    expect(spies.end).toHaveBeenCalledTimes(1);
    expect(logger.error).toHaveBeenCalledWith(
      expect.stringContaining("PAM authentication failed")
    );
  });

  it("logs elapsed time per table and in the summary", async () => {
    let clock = 0;
    const { client } = makeClient({
      tables: ["document"],
      tableColumns: { document: [col({ column_name: "id" })] },
    });
    const logger = makeLogger();

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger,
      env: {},
      now: () => {
        clock += 10;
        return clock;
      },
    });

    expect(logger.log).toHaveBeenCalledWith(
      expect.stringMatching(PER_TABLE_TIMING_LOG)
    );
    expect(logger.log).toHaveBeenCalledWith(
      expect.stringMatching(CLONE_SUMMARY_TIMING_LOG)
    );
  });
});

describe("cloneDataFromPublic — FK cycles (ISS-5344)", () => {
  it("defers target FK checks before inserting cyclic tables", async () => {
    const alphaAlter = `ALTER TABLE "${PREVIEW_SCHEMA}"."alpha" ALTER CONSTRAINT "alpha_beta_fkey" DEFERRABLE INITIALLY IMMEDIATE`;
    const betaAlter = `ALTER TABLE "${PREVIEW_SCHEMA}"."beta" ALTER CONSTRAINT "beta_alpha_fkey" DEFERRABLE INITIALLY IMMEDIATE`;
    const alphaRestore = `ALTER TABLE "${PREVIEW_SCHEMA}"."alpha" ALTER CONSTRAINT "alpha_beta_fkey" NOT DEFERRABLE`;
    const betaRestore = `ALTER TABLE "${PREVIEW_SCHEMA}"."beta" ALTER CONSTRAINT "beta_alpha_fkey" NOT DEFERRABLE`;
    const { client, issued } = makeClient({
      tables: ["alpha", "beta"],
      fkEdges: [
        { child: "alpha", parent: "beta" },
        { child: "beta", parent: "alpha" },
      ],
      targetFkConstraints: [
        { table_name: "alpha", constraint_name: "alpha_beta_fkey" },
        { table_name: "beta", constraint_name: "beta_alpha_fkey" },
      ],
      tableColumns: {
        alpha: [col({ column_name: "id" }), col({ column_name: "beta_id" })],
        beta: [col({ column_name: "id" }), col({ column_name: "alpha_id" })],
      },
      requireDeferredBeforeInsert: true,
    });

    const result = await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger: makeLogger(),
      env: {},
    });

    const beginIndex = issued.indexOf("BEGIN");
    const alphaAlterIndex = issued.indexOf(alphaAlter);
    const betaAlterIndex = issued.indexOf(betaAlter);
    const setDeferredIndex = issued.indexOf("SET CONSTRAINTS ALL DEFERRED");
    const setImmediateIndex = issued.indexOf("SET CONSTRAINTS ALL IMMEDIATE");
    const alphaRestoreIndex = issued.indexOf(alphaRestore);
    const betaRestoreIndex = issued.indexOf(betaRestore);
    const firstInsertIndex = issued.findIndex((sql) =>
      sql.startsWith("INSERT INTO")
    );
    const lastInsertIndex = issued.reduce(
      (latest, sql, index) => (sql.startsWith("INSERT INTO") ? index : latest),
      -1
    );

    expect(result).toBe(true);
    expect(beginIndex).toBeGreaterThanOrEqual(0);
    expect(alphaAlterIndex).toBeGreaterThan(beginIndex);
    expect(betaAlterIndex).toBeGreaterThan(alphaAlterIndex);
    expect(setDeferredIndex).toBeGreaterThan(betaAlterIndex);
    expect(firstInsertIndex).toBeGreaterThan(setDeferredIndex);
    expect(setImmediateIndex).toBeGreaterThan(lastInsertIndex);
    expect(alphaRestoreIndex).toBeGreaterThan(setImmediateIndex);
    expect(betaRestoreIndex).toBeGreaterThan(alphaRestoreIndex);
    expect(issued.indexOf("COMMIT")).toBeGreaterThan(betaRestoreIndex);
    expect(issued).not.toContain("ROLLBACK");
  });
});

describe("cloneDataFromPublic — generated columns (ISS-5285)", () => {
  it("omits a GENERATED ALWAYS column from BOTH the INSERT and SELECT lists", async () => {
    const { client, issued } = makeClient({
      tables: ["search_documents"],
      tableColumns: {
        search_documents: [
          col({ column_name: "id" }),
          col({ column_name: "title" }),
          col({ column_name: "tsv", generated: "s" }),
        ],
      },
    });

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger: makeLogger(),
      env: {},
    });

    const insert = issued.find((sql) => sql.startsWith("INSERT INTO"));
    expect(insert).toBeDefined();
    expect(insert).toContain('"id"');
    expect(insert).toContain('"title"');
    expect(insert).not.toContain("tsv");
  });

  it("keeps the USER-DEFINED enum cast intact alongside the generated-column filter", async () => {
    const { client, issued } = makeClient({
      tables: ["document"],
      tableColumns: {
        document: [
          col({ column_name: "id" }),
          col({
            column_name: "status",
            is_enum: true,
            enum_type: "DocumentStatus",
          }),
          col({ column_name: "tsv", generated: "s" }),
        ],
      },
    });

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger: makeLogger(),
      env: {},
    });

    const insert = issued.find((sql) => sql.startsWith("INSERT INTO"));
    expect(insert).toContain(
      `"status"::text::"${PREVIEW_SCHEMA}"."DocumentStatus"`
    );
    expect(insert).not.toContain("tsv");
  });

  it("bridges an ARRAY of an enum through text[] (custom_fields.entity_types)", async () => {
    const { client, issued } = makeClient({
      tables: ["custom_fields"],
      tableColumns: {
        custom_fields: [
          col({ column_name: "id" }),
          // The column's own pg_type row is the array wrapper (typtype 'b');
          // the enum-ness is one hop away via typelem.
          col({
            column_name: "entity_types",
            is_enum_array: true,
            enum_type: "CustomFieldEntityType",
          }),
        ],
      },
    });

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger: makeLogger(),
      env: {},
    });

    const insert = issued.find((sql) => sql.startsWith("INSERT INTO"));
    expect(insert).toContain(
      `"entity_types"::text[]::"${PREVIEW_SCHEMA}"."CustomFieldEntityType"[]`
    );
  });

  it("skips a table whose only non-generated columns are absent from source (no empty INSERT)", async () => {
    const { client, issued } = makeClient({
      tables: ["odd_table"],
      tableColumns: {
        odd_table: [
          col({ column_name: "only_in_target" }),
          col({ column_name: "tsv", generated: "s" }),
        ],
      },
      // `tsv` exists in source, `only_in_target` does not — so after the
      // generated filter there is nothing left to clone.
      sourceColumnNames: { odd_table: ["tsv"] },
    });
    const logger = makeLogger();

    await cloneDataFromPublic(DATABASE_URL, PREVIEW_SCHEMA, {
      createClient: () => client,
      logger,
      env: {},
    });

    expect(issued.some((sql) => sql.startsWith("INSERT INTO"))).toBe(false);
    expect(logger.warn).toHaveBeenCalledWith(
      expect.stringContaining("no overlapping columns")
    );
  });
});
