"use client";

import { useRouter } from "next/navigation";
import { DataTable, type Column, type SortOption, type FilterOption } from "@repo/design-system/components/ui/data-table";
import type { ImplementationPlan, PRD } from "@repo/database/generated/client";
import { ImplementationPlanStatusBadge } from "./implementation-plan-status-badge";
import { ImplementationPlanRowActions } from "./implementation-plan-row-actions";

type ImplementationPlanWithPRD = ImplementationPlan & {
  sourcePrd: Pick<PRD, "id" | "title">;
};

type ImplementationPlanTableProps = {
  plans: ImplementationPlanWithPRD[];
};

const columns: Column<ImplementationPlanWithPRD>[] = [
  {
    key: "title",
    header: "Plan Name / Source PRD",
    render: (plan) => (
      <div className="flex flex-col">
        <span className="font-medium">{plan.title}</span>
        <span className="text-sm text-muted-foreground">{plan.sourcePrd.title}</span>
      </div>
    ),
  },
  {
    key: "version",
    header: "Version",
    render: (plan) => <span className="font-mono text-sm">v{plan.version}</span>,
  },
  {
    key: "generatedBy",
    header: "Generated By",
  },
  {
    key: "createdAt",
    header: "Generated",
    render: (plan) => formatDate(plan.createdAt),
  },
  {
    key: "status",
    header: "Status",
    render: (plan) => <ImplementationPlanStatusBadge status={plan.status} />,
  },
];

const sortOptions: SortOption[] = [
  { label: "Recently Generated", value: "createdAt:desc" },
  { label: "Oldest First", value: "createdAt:asc" },
  { label: "Name A-Z", value: "title:asc" },
  { label: "Name Z-A", value: "title:desc" },
  { label: "Version (High to Low)", value: "version:desc" },
  { label: "Version (Low to High)", value: "version:asc" },
];

const filterOptions: FilterOption[] = [
  { label: "Draft", value: "Draft" },
  { label: "Ready", value: "Ready" },
  { label: "In Progress", value: "In Progress" },
  { label: "Generating", value: "Generating" },
  { label: "Failed", value: "Failed" },
  { label: "Archived", value: "Archived" },
];

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(date));
}

export function ImplementationPlanTable({ plans }: ImplementationPlanTableProps) {
  const router = useRouter();

  const handleRowClick = (plan: ImplementationPlanWithPRD) => {
    router.push(`/implementation-plans/${plan.id}`);
  };

  return (
    <DataTable
      data={plans}
      columns={columns}
      searchPlaceholder="Search implementation plans"
      searchKey="title"
      sortOptions={sortOptions}
      filterOptions={filterOptions}
      filterKey="status"
      onRowClick={handleRowClick}
      renderRowActions={(plan) => <ImplementationPlanRowActions plan={plan} />}
      emptyMessage="No implementation plans found. Generate your first plan from a PRD to get started."
    />
  );
}
