/**
 * ISS-5299 — Branch coverage for symphony-interactive.ts and symphony-plan-loop.ts.
 *
 * This file is a flat sibling suite (not appended to gateway-server.test.ts,
 * which is on the shrink-only grandfathered list) targeting validation-rejection
 * branches that gate access to the local filesystem — SECURITY CRITICAL surface.
 *
 * Covers:
 *   symphony-interactive.ts
 *     - sanitizeCommitMessage: full input space of the pure exported function
 *     - POST /api/gateway/symphony/chat/:ticketId — invalid body, missing fields,
 *       disallowed dir, bad provider, worktree outside allowed boundary
 *     - GET /api/gateway/symphony/comment-chat/:commentId — missing params, disallowed dir
 *     - GET /api/gateway/symphony/commit-message/:ticketId — missing repo param,
 *       disallowed dir, worktree outside allowed boundary
 *     - POST /api/gateway/symphony/launch — invalid body, missing fields, disallowed dir,
 *       disallowed context repo, worktree parent boundary
 *   symphony-plan-loop.ts
 *     - POST /api/gateway/symphony/plan-loop/:ticketId/cancel — invalid body, missing
 *       fields, disallowed dir, no API key, fetch throws, API error response, no PID found
 */
import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import fs from "node:fs/promises";
import { afterEach, test } from "node:test";
import { createStubJobStore } from "../src/main/jobs/job-store.js";
import type { RetrySpawnDeps } from "../src/main/util/spawn-retry.js";
import { OperationDispatcher } from "../src/server/operation-dispatcher.js";
import {
  registerSymphonyInteractiveRoutes,
  sanitizeCommitMessage,
} from "../src/server/operations/symphony-interactive.js";
import { registerSymphonyPlanLoopRoutes } from "../src/server/operations/symphony-plan-loop.js";
import { resolveWorktreeDir } from "../src/server/operations/symphony-utils.js";
import type { ClaudeCodeShellEnvProvider } from "../src/server/otel/claude-code-env.js";
import {
  createGitOpTempDirs,
  dispatchOperation,
  pinDefaultWorktreeParentDir,
} from "./helpers/git-gateway-op-harness.js";

// resolveWorktreeDir prefers SYMPHONY_WORKTREE_PARENT_DIR over the default
// dirname(repoPath) branch these fixtures are built for, so pin it unset.
pinDefaultWorktreeParentDir();

// ---------------------------------------------------------------------------
// Module-level stubs
// ---------------------------------------------------------------------------

const stubDeps: RetrySpawnDeps = {
  log: () => {},
  refreshTray: () => {},
  isShuttingDown: () => false,
  delay: () => Promise.resolve(),
};

const stubShellEnv: ClaudeCodeShellEnvProvider = async () => ({});

// Save original fetch so afterEach can restore it.
const originalFetch = globalThis.fetch;

afterEach(() => {
  globalThis.fetch = originalFetch;
});

const { makeTempDir } = createGitOpTempDirs("iss5299-sio-");

// ---------------------------------------------------------------------------
// Dispatcher factories
// ---------------------------------------------------------------------------

function makeInteractiveDispatcher(allowedDir: string): OperationDispatcher {
  const dispatcher = new OperationDispatcher();
  registerSymphonyInteractiveRoutes(
    dispatcher,
    () => [allowedDir],
    stubDeps,
    stubShellEnv
  );
  return dispatcher;
}

function makePlanLoopDispatcher(
  allowedDir: string,
  getApiKey: () => string | null = () => "sk_test_key"
): OperationDispatcher {
  const dispatcher = new OperationDispatcher();
  registerSymphonyPlanLoopRoutes(
    dispatcher,
    () => [allowedDir],
    getApiKey,
    () => "http://localhost:3002",
    createStubJobStore()
  );
  return dispatcher;
}

// ---------------------------------------------------------------------------
// sanitizeCommitMessage — pure exported function
// ---------------------------------------------------------------------------

test("sanitizeCommitMessage: empty string returns empty string", () => {
  assert.equal(sanitizeCommitMessage(""), "");
});

test("sanitizeCommitMessage: whitespace-only string trims to empty", () => {
  assert.equal(sanitizeCommitMessage("   "), "");
});

test("sanitizeCommitMessage: strips 'Claude Code' case-insensitively", () => {
  assert.equal(
    sanitizeCommitMessage("Generated by Claude Code"),
    "Generated by"
  );
});

test("sanitizeCommitMessage: strips 'claude code' with irregular spacing", () => {
  assert.equal(sanitizeCommitMessage("claude  code suggestion"), "suggestion");
});

test("sanitizeCommitMessage: strips standalone 'claude' word boundary", () => {
  assert.equal(sanitizeCommitMessage("claude did this"), "did this");
});

test("sanitizeCommitMessage: strips 'Sonnet' at word boundary", () => {
  assert.equal(sanitizeCommitMessage("via Sonnet 3.5"), "via 3.5");
});

test("sanitizeCommitMessage: strips 'Haiku' at word boundary", () => {
  assert.equal(sanitizeCommitMessage("haiku model used"), "model used");
});

test("sanitizeCommitMessage: strips 'opus' at word boundary", () => {
  assert.equal(sanitizeCommitMessage("using Opus"), "using");
});

test("sanitizeCommitMessage: does not strip 'octopus' (contains 'opus' but not at boundary)", () => {
  assert.equal(
    sanitizeCommitMessage("refactor octopus module"),
    "refactor octopus module"
  );
});

test("sanitizeCommitMessage: strips 'Anthropic' at word boundary", () => {
  assert.equal(sanitizeCommitMessage("Anthropic API policy"), "API policy");
});

test("sanitizeCommitMessage: strips 'AI assistant' case-insensitively", () => {
  assert.equal(sanitizeCommitMessage("built by AI Assistant"), "built by");
});

test("sanitizeCommitMessage: collapses runs of spaces and tabs to single space", () => {
  assert.equal(sanitizeCommitMessage("fix   the\t\tbug"), "fix the bug");
});

test("sanitizeCommitMessage: strips multiple vendor terms and normalises whitespace", () => {
  const input = "Generated by Claude Code via Sonnet using Anthropic API";
  assert.equal(sanitizeCommitMessage(input), "Generated by via using API");
});

test("sanitizeCommitMessage: plain text with no vendor terms is returned unchanged", () => {
  const plain = "fix: correct off-by-one in pagination logic";
  assert.equal(sanitizeCommitMessage(plain), plain);
});

test("sanitizeCommitMessage: trailing newline is trimmed", () => {
  assert.equal(sanitizeCommitMessage("some work\n"), "some work");
});

// ---------------------------------------------------------------------------
// POST /api/gateway/symphony/chat/:ticketId — validation branches
// ---------------------------------------------------------------------------

test("POST /symphony/chat — invalid JSON body returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/chat/ISS-1234",
    body: "not-json{{{",
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "Invalid JSON body");
});

test("POST /symphony/chat — missing message returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/chat/ISS-1234",
    body: JSON.stringify({ repoPath: tmpDir }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "message and repoPath are required");
});

test("POST /symphony/chat — missing repoPath returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/chat/ISS-1234",
    body: JSON.stringify({ message: "hello" }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "message and repoPath are required");
});

test("POST /symphony/chat — disallowed repoPath returns 403", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/chat/ISS-1234",
    body: JSON.stringify({ message: "hello", repoPath: "/etc" }),
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

test("POST /symphony/chat — unsupported provider returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/chat/ISS-1234",
    body: JSON.stringify({
      message: "hello",
      repoPath: tmpDir,
      provider: "gpt4",
    }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "unsupported provider");
});

test("POST /symphony/chat — existing worktree outside allowed boundary returns 403", async () => {
  // resolveWorktreeDir puts the worktree as a sibling of tmpDir (same parent).
  // A sibling is outside [tmpDir], so once it exists the inner assertPathAllowed fails.
  const tmpDir = makeTempDir();
  const worktreeDir = resolveWorktreeDir(tmpDir, "ISS-1234");
  mkdirSync(worktreeDir, { recursive: true });
  try {
    const dispatcher = makeInteractiveDispatcher(tmpDir);
    const res = await dispatchOperation({
      dispatcher,
      method: "POST",
      pathname: "/api/gateway/symphony/chat/ISS-1234",
      body: JSON.stringify({ message: "hello", repoPath: tmpDir }),
    });
    assert.equal(res.statusCode, 403);
    assert.equal(res.body.error, "directory not allowed");
  } finally {
    await fs.rm(worktreeDir, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// GET /api/gateway/symphony/comment-chat/:commentId — validation branches
// ---------------------------------------------------------------------------

test("GET /symphony/comment-chat — missing ticketId returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "GET",
    pathname: "/api/gateway/symphony/comment-chat/comment-abc",
    query: { repo: tmpDir },
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "ticketId and repo parameters are required");
});

test("GET /symphony/comment-chat — missing repo returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "GET",
    pathname: "/api/gateway/symphony/comment-chat/comment-abc",
    query: { ticketId: "ISS-1234" },
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "ticketId and repo parameters are required");
});

test("GET /symphony/comment-chat — disallowed repo returns 403", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "GET",
    pathname: "/api/gateway/symphony/comment-chat/comment-abc",
    query: { ticketId: "ISS-1234", repo: "/etc" },
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

// ---------------------------------------------------------------------------
// GET /api/gateway/symphony/commit-message/:ticketId — validation branches
// ---------------------------------------------------------------------------

test("GET /symphony/commit-message — missing repo param returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "GET",
    pathname: "/api/gateway/symphony/commit-message/ISS-1234",
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "repo query parameter is required");
});

test("GET /symphony/commit-message — disallowed repo returns 403", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "GET",
    pathname: "/api/gateway/symphony/commit-message/ISS-1234",
    query: { repo: "/etc" },
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

test("GET /symphony/commit-message — existing worktree outside allowed boundary returns 403", async () => {
  // Same boundary exploit as the chat test: worktree is a sibling of tmpDir.
  const tmpDir = makeTempDir();
  const worktreeDir = resolveWorktreeDir(tmpDir, "ISS-1234");
  mkdirSync(worktreeDir, { recursive: true });
  try {
    const dispatcher = makeInteractiveDispatcher(tmpDir);
    const res = await dispatchOperation({
      dispatcher,
      method: "GET",
      pathname: "/api/gateway/symphony/commit-message/ISS-1234",
      query: { repo: tmpDir },
    });
    assert.equal(res.statusCode, 403);
    assert.equal(res.body.error, "directory not allowed");
  } finally {
    await fs.rm(worktreeDir, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// POST /api/gateway/symphony/launch — validation branches
// ---------------------------------------------------------------------------

test("POST /symphony/launch — invalid JSON body returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: "{{bad json",
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "Invalid JSON body");
});

test("POST /symphony/launch — missing ticketIdentifier returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: JSON.stringify({ repoPath: tmpDir }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(
    res.body.error,
    "ticketIdentifier is required and must be a string"
  );
});

test("POST /symphony/launch — missing repoPath returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: JSON.stringify({ ticketIdentifier: "ISS-1234" }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "repoPath is required and must be a string");
});

test("POST /symphony/launch — disallowed repoPath returns 403", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: JSON.stringify({ ticketIdentifier: "ISS-1234", repoPath: "/etc" }),
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

test("POST /symphony/launch — disallowed context repo returns 403", async () => {
  // contextRepoPaths inside ticket object — assertAllReposAllowed rejects "/etc".
  // This also exercises the assertAllReposAllowed error-return branch (line 86).
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: JSON.stringify({
      ticketIdentifier: "ISS-1234",
      repoPath: tmpDir,
      ticket: { contextRepoPaths: ["/etc"] },
    }),
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

test("POST /symphony/launch — worktree parent outside allowed boundary returns 403", async () => {
  // resolveWorktreeDir returns a sibling of tmpDir; its dirname (the OS tmpdir)
  // is NOT within [tmpDir], so tryAssertPathAllowed rejects it.
  const tmpDir = makeTempDir();
  const dispatcher = makeInteractiveDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/launch",
    body: JSON.stringify({ ticketIdentifier: "ISS-1234", repoPath: tmpDir }),
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

// ---------------------------------------------------------------------------
// POST /api/gateway/symphony/plan-loop/:ticketId/cancel — validation branches
// ---------------------------------------------------------------------------

test("POST /plan-loop/cancel — invalid JSON body returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: "{bad",
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "Invalid JSON body");
});

test("POST /plan-loop/cancel — missing repoPath returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ loopId: "loop-abc" }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "repoPath is required");
});

test("POST /plan-loop/cancel — missing loopId returns 400", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: tmpDir }),
  });
  assert.equal(res.statusCode, 400);
  assert.equal(res.body.error, "loopId is required");
});

test("POST /plan-loop/cancel — disallowed repoPath returns 403", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: "/etc", loopId: "loop-abc" }),
  });
  assert.equal(res.statusCode, 403);
  assert.equal(res.body.error, "directory not allowed");
});

test("POST /plan-loop/cancel — no API key configured returns 503", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir, () => null);
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: tmpDir, loopId: "loop-abc" }),
  });
  assert.equal(res.statusCode, 503);
  assert.equal(res.body.error, "API key not configured");
});

test("POST /plan-loop/cancel — fetch throws returns 502 with error message", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  globalThis.fetch = ((
    _input: RequestInfo | URL,
    _init?: RequestInit
  ): Promise<Response> =>
    Promise.reject(new Error("network unreachable"))) as typeof fetch;
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: tmpDir, loopId: "loop-abc" }),
  });
  assert.equal(res.statusCode, 502);
  assert.ok(
    String(res.body.error).includes("network unreachable"),
    `expected error to include 'network unreachable', got: ${res.body.error}`
  );
});

test("POST /plan-loop/cancel — API returns 500 propagates that status", async () => {
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  globalThis.fetch = (async (
    _input: RequestInfo | URL,
    _init?: RequestInit
  ): Promise<Response> =>
    new Response("server broke", { status: 500 })) as typeof fetch;
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: tmpDir, loopId: "loop-abc" }),
  });
  assert.equal(res.statusCode, 500);
  assert.ok(
    String(res.body.error).includes("DB cancel failed"),
    `expected error to include 'DB cancel failed', got: ${res.body.error}`
  );
});

test("POST /plan-loop/cancel — API ok with no PID found returns cancelled with process-unknown warning", async () => {
  // fetch succeeds; no PID file exists for the worktree; getActiveLoopPid returns
  // null for an unknown loop; stub job store has no record → process-unknown.
  const tmpDir = makeTempDir();
  const dispatcher = makePlanLoopDispatcher(tmpDir);
  globalThis.fetch = (async (
    _input: RequestInfo | URL,
    _init?: RequestInit
  ): Promise<Response> => new Response("", { status: 200 })) as typeof fetch;
  const res = await dispatchOperation({
    dispatcher,
    method: "POST",
    pathname: "/api/gateway/symphony/plan-loop/ISS-1234/cancel",
    body: JSON.stringify({ repoPath: tmpDir, loopId: "loop-xyz-unknown" }),
  });
  assert.equal(res.statusCode, 200);
  assert.equal(res.body.cancelled, true);
  assert.equal(res.body.warning, "process-unknown");
});
