-- Split the shared artifact status vocabulary into DocumentStatus + FeatureStatus (PRD-495).
--
-- Two independent parts:
--   1. Advisory enum DDL. `Artifact.status` is a freeform String column and is
--      NOT bound to either enum, so these CREATE/ALTER TYPE statements only keep
--      the decorative `DocumentStatus` / `FeatureStatus` Postgres types in sync
--      with schema.prisma. No column is rewritten. The DDL below is exactly what
--      `prisma migrate diff` generates for the schema change (reproduced by hand
--      because no database was reachable at authoring time to run `migrate dev`).
--   2. A per-subtype data backfill of the freeform `artifacts.status` column.
--      Hand-written DML is permitted (data migration). The backfill is LOSSY and
--      IRREVERSIBLE — e.g. document DONE collapses into APPROVED, and feature
--      EXECUTED/DONE both land on DONE. Snapshot `artifacts(id, status, subtype)`
--      before applying. Branch / Deployment / Session rows are left UNTOUCHED.

-- 1. Advisory enums (generated by `prisma migrate diff`) --------------------

-- CreateEnum
CREATE TYPE "FeatureStatus" AS ENUM ('TRIAGE', 'BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'BLOCKED', 'DONE', 'CANCELED');

-- AlterEnum
BEGIN;
CREATE TYPE "DocumentStatus_new" AS ENUM ('DRAFT', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'EXECUTED', 'OBSOLETE');
ALTER TYPE "DocumentStatus" RENAME TO "DocumentStatus_old";
ALTER TYPE "DocumentStatus_new" RENAME TO "DocumentStatus";
DROP TYPE "DocumentStatus_old";
COMMIT;

-- 2. Per-subtype status backfill (data migration) ---------------------------

-- Documents (subtype IN PRD/IMPLEMENTATION_PLAN/TEMPLATE):
--   IN_PROGRESS -> DRAFT (absorbed), DONE -> APPROVED (done implied by approved).
--   DRAFT/IN_REVIEW/APPROVED/EXECUTED/OBSOLETE keep their value (no-op, omitted).
UPDATE "artifacts"
SET "status" = 'DRAFT'
WHERE "type" = 'DOCUMENT'
  AND "subtype" IN ('PRD', 'IMPLEMENTATION_PLAN', 'TEMPLATE')
  AND "status" = 'IN_PROGRESS';

UPDATE "artifacts"
SET "status" = 'APPROVED'
WHERE "type" = 'DOCUMENT'
  AND "subtype" IN ('PRD', 'IMPLEMENTATION_PLAN', 'TEMPLATE')
  AND "status" = 'DONE';

-- Features (subtype = FEATURE):
--   DRAFT -> BACKLOG, APPROVED -> TODO, EXECUTED -> DONE, OBSOLETE -> CANCELED.
--   IN_PROGRESS/IN_REVIEW/DONE keep their value (no-op, omitted).
--   TRIAGE is net-new; no source status maps to it.
UPDATE "artifacts"
SET "status" = 'BACKLOG'
WHERE "type" = 'DOCUMENT'
  AND "subtype" = 'FEATURE'
  AND "status" = 'DRAFT';

UPDATE "artifacts"
SET "status" = 'TODO'
WHERE "type" = 'DOCUMENT'
  AND "subtype" = 'FEATURE'
  AND "status" = 'APPROVED';

UPDATE "artifacts"
SET "status" = 'DONE'
WHERE "type" = 'DOCUMENT'
  AND "subtype" = 'FEATURE'
  AND "status" = 'EXECUTED';

UPDATE "artifacts"
SET "status" = 'CANCELED'
WHERE "type" = 'DOCUMENT'
  AND "subtype" = 'FEATURE'
  AND "status" = 'OBSOLETE';
