-- AlterTable
ALTER TABLE "session_detail" ADD COLUMN     "active_agent" TEXT,
ADD COLUMN     "activity_buckets" JSONB,
ADD COLUMN     "autonomy" INTEGER,
ADD COLUMN     "branch" TEXT,
ADD COLUMN     "files_changed" INTEGER,
ADD COLUMN     "issues" JSONB,
ADD COLUMN     "lines_added" INTEGER,
ADD COLUMN     "lines_removed" INTEGER,
ADD COLUMN     "markers" JSONB,
ADD COLUMN     "phase_iterations" JSONB,
ADD COLUMN     "phase_loopbacks" JSONB,
ADD COLUMN     "phases" JSONB,
ADD COLUMN     "pull_requests" JSONB,
ADD COLUMN     "session_span" JSONB,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "steering_episodes" INTEGER,
ADD COLUMN     "throttles" JSONB,
ADD COLUMN     "turns" INTEGER,
ADD COLUMN     "waiting_user" TEXT,
ADD COLUMN     "wall_clock" TEXT;
